/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * An iterator through the arguments of a term.
 */
public class ArgumentIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArgumentIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArgumentIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ArgumentIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_ArgumentIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Is this iterator pointing to a valid argument?
   */
  public boolean valid() {
    return maudeJNI.ArgumentIterator_valid(swigCPtr, this);
  }

  /**
   * Advance the iterator to the next argument.
   */
  public void __next() {
    maudeJNI.ArgumentIterator___next(swigCPtr, this);
  }

  /**
   * Get the argument pointed by this iterator.
   */
  public Term argument() {
    long cPtr = maudeJNI.ArgumentIterator_argument(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

}
