/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * An assignment <code>t := t'</code> condition.
 */
public class AssignmentCondition extends ConditionFragment {
  private transient long swigCPtr;

  protected AssignmentCondition(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.AssignmentCondition_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AssignmentCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AssignmentCondition obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_AssignmentCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AssignmentCondition(Term lhs, Term rhs) {
    this(maudeJNI.new_AssignmentCondition(Term.getCPtr(lhs), lhs, Term.getCPtr(rhs), rhs), true);
  }

  /**
   * Get the left-hand-side term.
   */
  public Term getLhs() {
    long cPtr = maudeJNI.AssignmentCondition_getLhs(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the right-hand-side term.
   */
  public Term getRhs() {
    long cPtr = maudeJNI.AssignmentCondition_getRhs(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  public String toString() {
    return maudeJNI.AssignmentCondition_toString(swigCPtr, this);
  }

}
