/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A Maude equation.
 */
public class Equation extends ModuleItem {
  private transient long swigCPtr;

  protected Equation(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.Equation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Equation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Equation obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Equation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the left-hand-side term.
   */
  public Term getLhs() {
    long cPtr = maudeJNI.Equation_getLhs(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the right-hand-side term.
   */
  public Term getRhs() {
    long cPtr = maudeJNI.Equation_getRhs(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the label attribute.
   */
  public String getLabel() {
    return maudeJNI.Equation_getLabel(swigCPtr, this);
  }

  /**
   * Whether the equation has the <code>nonexec</code> attribute.
   */
  public boolean isNonexec() {
    return maudeJNI.Equation_isNonexec(swigCPtr, this);
  }

  /**
   * Whether the equation has the <code>owise</code> attribute.
   */
  public boolean isOwise() {
    return maudeJNI.Equation_isOwise(swigCPtr, this);
  }

  /**
   * Whether the equation has the <code>variant</code> attribute.
   */
  public boolean isVariant() {
    return maudeJNI.Equation_isVariant(swigCPtr, this);
  }

  /**
   * Whether the equation has a condition.
   */
  public boolean hasCondition() {
    return maudeJNI.Equation_hasCondition(swigCPtr, this);
  }

  /**
   * Get the condition of the equation.
   */
  public Condition getCondition() {
    return new Condition(maudeJNI.Equation_getCondition(swigCPtr, this), false);
  }

  public String toString() {
    return maudeJNI.Equation_toString(swigCPtr, this);
  }

  /**
   * Get the free text <code>metadata</code> attribute of this statement.
   */
  public String getMetadata() {
    return maudeJNI.Equation_getMetadata(swigCPtr, this);
  }

  /**
   * Get the line number information for this item as formatted by Maude.<br>
   * <br>
   * The format of the string is usually <code>filename, line line (module)</code><br>
   * where the second <code>line</code> is the integral line number, and <code>module</code> is<br>
   * the module type and name where this item was originally defined. The<br>
   * <code>filename</code> may be an actual quoted filename or some special name<br>
   * between angle brackets.
   */
  public String getLineNumber() {
    return maudeJNI.Equation_getLineNumber(swigCPtr, this);
  }

  /**
   * Get the hash value of the equation.
   */
  public long hash() {
    return maudeJNI.Equation_hash(swigCPtr, this);
  }

  /**
   * Check whether two equation are the same.
   */
  public boolean equal(Equation other) {
    return maudeJNI.Equation_equal(swigCPtr, this, Equation.getCPtr(other), other);
  }

}
