/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Special operators defined on the external language.
 */
public class Hook {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Hook(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Hook obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Hook obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Hook(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    maudeJNI.Hook_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    maudeJNI.Hook_change_ownership(this, swigCPtr, true);
  }

  /**
   * Method called by the hook.<br>
   * <br>
   * @param term The term being reduced or rewritten.<br>
   * @param data Data associated to the hook.<br>
   * <br>
   * @return The reduced or rewritten term, or a null value in case<br>
   * no rewrite is possible.
   */
  public Term run(Term term, HookData data) {
    long cPtr = maudeJNI.Hook_run(swigCPtr, this, Term.getCPtr(term), term, HookData.getCPtr(data), data);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  public Hook() {
    this(maudeJNI.new_Hook(), true);
    maudeJNI.Hook_director_connect(this, swigCPtr, true, true);
  }

}
