/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Data associated to a hook and passed to its callback.
 */
public class HookData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HookData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HookData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HookData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_HookData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Get the data associated to the hook.
   */
  public StringVector getData() {
    return new StringVector(maudeJNI.HookData_getData(swigCPtr, this), false);
  }

  /**
   * Get the symbol associated to the hook with the given name.
   */
  public Symbol getSymbol(String name) {
    long cPtr = maudeJNI.HookData_getSymbol(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Symbol(cPtr, true);
  }

  /**
   * Get the term associated to the hook with the given name.
   */
  public Term getTerm(String name) {
    long cPtr = maudeJNI.HookData_getTerm(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

}
