/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class Iterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Iterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Iterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Iterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void nextAssignment() {
    maudeJNI.Iterator_nextAssignment(swigCPtr, this);
  }

  public Term getVariable() {
    long cPtr = maudeJNI.Iterator_getVariable(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  public Term getValue() {
    long cPtr = maudeJNI.Iterator_getValue(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

}
