/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A Maude kind (connected component of sorts).
 */
public class Kind {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Kind(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Kind obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Kind obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Kind(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Get the number of sorts in this kind.
   */
  public int nrSorts() {
    return maudeJNI.Kind_nrSorts(swigCPtr, this);
  }

  /**
   * Get the number of maximal sorts in this kind.
   */
  public int nrMaximalSorts() {
    return maudeJNI.Kind_nrMaximalSorts(swigCPtr, this);
  }

  /**
   * Get the sort with a given index in this kind.<br>
   * <br>
   * @param index Sort index.
   */
  public Sort sort(int index) {
    long cPtr = maudeJNI.Kind_sort(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Sort(cPtr, true);
  }

  /**
   * Whether the kind contains error terms.
   */
  public boolean errorFree() {
    return maudeJNI.Kind_errorFree(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.Kind_toString(swigCPtr, this);
  }

  /**
   * Get the hash value of the kind.
   */
  public long hash() {
    return maudeJNI.Kind_hash(swigCPtr, this);
  }

  /**
   * Check whether two kind are the same.
   */
  public boolean equal(Kind other) {
    return maudeJNI.Kind_equal(swigCPtr, this, Kind.getCPtr(other), other);
  }

}
