/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

		import java.util.Iterator;
		import java.util.NoSuchElementException;
	
/**
 * An iterator through the matching a term into a pattern.
 */
public class MatchSearchState implements Iterable<Substitution>, Iterator<Substitution> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MatchSearchState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MatchSearchState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MatchSearchState obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_MatchSearchState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

		private transient Substitution last = null;
		private transient boolean advanced = false;

		public Iterator<Substitution> iterator() {
			return this;
		}

		public boolean hasNext() {
			if (!advanced) {
				last = __next();
				advanced = true;
			}
			return last != null;
		}

		public Substitution next() {
			if (!advanced)
				hasNext();
			if (last == null)
				throw new NoSuchElementException("no more solutions");
			advanced = false;
			return last;
		}
	
  /**
   * Get the next match.<br>
   * <br>
   * @return A matching substitution or null pointer if<br>
   * there is no more matches.
   */
  public Substitution __next() {
    long cPtr = maudeJNI.MatchSearchState___next(swigCPtr, this);
    return (cPtr == 0) ? null : new Substitution(cPtr, true);
  }

  /**
   * Get the context of the match filled with the given term.<br>
   * <br>
   * @param term Term to fill the context.<br>
   * <br>
   * @return The original term with the matched subterm replaced by the given term.
   */
  public Term fillContext(Term term) {
    long cPtr = maudeJNI.MatchSearchState_fillContext(swigCPtr, this, Term.getCPtr(term), term);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

}
