/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class maude implements maudeConstants {
  /**
   * Init Maude.<br>
   * <br>
   * This function must be called before anything else.<br>
   * <br>
   * @param loadPrelude Whether the Maude prelude should be loaded.<br>
   * @param randomSeed Seed for the pseudorandom number generator in<br>
   * the <code>RANDOM</code> module.<br>
   * @param advise Whether debug messages should be printed.<br>
   * @param handleInterrupts Whether interrupts are handled by Maude.
   */
  public static boolean init(boolean loadPrelude, int randomSeed, boolean advise, boolean handleInterrupts) {
    return maudeJNI.init__SWIG_0(loadPrelude, randomSeed, advise, handleInterrupts);
  }

  /**
   * Init Maude.<br>
   * <br>
   * This function must be called before anything else.<br>
   * <br>
   * @param loadPrelude Whether the Maude prelude should be loaded.<br>
   * @param randomSeed Seed for the pseudorandom number generator in<br>
   * the <code>RANDOM</code> module.<br>
   * @param advise Whether debug messages should be printed.<br>
   * 
   */
  public static boolean init(boolean loadPrelude, int randomSeed, boolean advise) {
    return maudeJNI.init__SWIG_1(loadPrelude, randomSeed, advise);
  }

  /**
   * Init Maude.<br>
   * <br>
   * This function must be called before anything else.<br>
   * <br>
   * @param loadPrelude Whether the Maude prelude should be loaded.<br>
   * @param randomSeed Seed for the pseudorandom number generator in<br>
   * the <code>RANDOM</code> module.<br>
   * <br>
   * 
   */
  public static boolean init(boolean loadPrelude, int randomSeed) {
    return maudeJNI.init__SWIG_2(loadPrelude, randomSeed);
  }

  /**
   * Init Maude.<br>
   * <br>
   * This function must be called before anything else.<br>
   * <br>
   * @param loadPrelude Whether the Maude prelude should be loaded.<br>
   * <br>
   * <br>
   * 
   */
  public static boolean init(boolean loadPrelude) {
    return maudeJNI.init__SWIG_3(loadPrelude);
  }

  /**
   * Init Maude.<br>
   * <br>
   * This function must be called before anything else.<br>
   * <br>
   * <br>
   * <br>
   * <br>
   * 
   */
  public static boolean init() {
    return maudeJNI.init__SWIG_4();
  }

  /**
   * Load the file with the given name.<br>
   * <br>
   * @param name The name of the file (absolute or relative to the current<br>
   * working directory or <code>MAUDE_LIB)</code>.
   */
  public static boolean load(String name) {
    return maudeJNI.load(name);
  }

  /**
   * Process the given text as direct input to Maude.<br>
   * <br>
   * @param text Maude modules or commands.
   */
  public static boolean input(String text) {
    return maudeJNI.input(text);
  }

  /**
   * Get the current module (the last module inserted or explicitly selected,<br>
   * like in the Maude interpreter).
   */
  public static Module getCurrentModule() {
    long cPtr = maudeJNI.getCurrentModule();
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  /**
   * Get a module or theory by name.<br>
   * <br>
   * @param name Name of the module or theory (module expressions are not allowed).
   */
  public static Module getModule(String name) {
    long cPtr = maudeJNI.getModule(name);
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  /**
   * Get a module object from its metarepresentation in this<br>
   * module, which must include the <code>META-LEVEL</code> module.<br>
   * <br>
   * @param term The metarepresentation of a module, that is,<br>
   * a valid element of the <code>Module</code> sort in <code>META-MODULE</code>.<br>
   * The term will be reduced.<br>
   * <br>
   * @return The module object or null if the given term was not<br>
   * a valid module metarepresentation.
   */
  public static Module downModule(Term term) {
    long cPtr = maudeJNI.downModule(Term.getCPtr(term), term);
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  /**
   * Tokenize a string according to Maude lexer rules.<br>
   * <br>
   * <br>
   * <br>
   * @return A vector of tokens.
   */
  public static TokenVector tokenize(String str) {
    return new TokenVector(maudeJNI.tokenize(str), true);
  }

  /**
   * Get the list of loaded modules.<br>
   * <br>
   * @return A list of module headers (this may change).
   */
  public static ModuleHeaderVector getModules() {
    return new ModuleHeaderVector(maudeJNI.getModules(), true);
  }

  /**
   * Get a view by name.<br>
   * <br>
   * @param name Name of the view (view expressions are not allowed).
   */
  public static View getView(String name) {
    long cPtr = maudeJNI.getView(name);
    return (cPtr == 0) ? null : new View(cPtr, false);
  }

  /**
   * Get the list of loaded views.
   */
  public static ViewVector getViews() {
    return new ViewVector(maudeJNI.getViews(), true);
  }

  /**
   * Allow or disallow running arbitrary executables from Maude code.<br>
   * <br>
   * @param flag Whether process creation should be allowed.
   */
  public static void setAllowProcesses(boolean flag) {
    maudeJNI.setAllowProcesses(flag);
  }

  /**
   * Allow or disallow operations on files from Maude code.<br>
   * <br>
   * @param flag Whether file access should be allowed.
   */
  public static void setAllowFiles(boolean flag) {
    maudeJNI.setAllowFiles(flag);
  }

  /**
   * Allow or disallow operations on directories from Maude code.<br>
   * <br>
   * @param flag Whether directory access should be allowed.
   */
  public static void setAllowDir(boolean flag) {
    maudeJNI.setAllowDir(flag);
  }

  /**
   * Set the pseudorandom number generator seed.<br>
   * <br>
   * 
   */
  public static void setRandomSeed(int randomSeed) {
    maudeJNI.setRandomSeed(randomSeed);
  }

  /**
   * Set depth multiplier for associative unification.<br>
   * <br>
   * 
   */
  public static boolean setAssocUnifDepth(float m) {
    return maudeJNI.setAssocUnifDepth(m);
  }

  /**
   * Connect a callback for the reduction of a special operator declared with<br>
   * the <code>SpecialHubSymbol</code> id-hook.<br>
   * <br>
   * @param name The name of the operator to be bound to this callback.<br>
   *   In case the id-hook contains arguments, the name is instead the first<br>
   *   of these. A null value may be passed to assign a default callback for<br>
   *   those operators without an explicitly associated one.<br>
   * @param hook An instance of a subclass of Hook defining its run method.<br>
   *   The object must be alive as long as the binding is active. A null value<br>
   *   can be passed to disconnect the current one.<br>
   * <br>
   * @return Whether this call overwrites a previous binding.
   */
  public static boolean connectEqHook(String name, Hook hook) {
    return maudeJNI.connectEqHook(name, Hook.getCPtr(hook), hook);
  }

  /**
   * Connect a callback for rule rewriting a special operator declared with<br>
   * the <code>SpecialHubSymbol</code> id-hook.<br>
   * <br>
   * @param name The name of the operator to be bound to this callback.<br>
   *   In case the id-hook contains arguments, the name is instead the first<br>
   *   of these. A null value may be passed to assign a default callback for<br>
   *   those operators without an explicitly associated one.<br>
   * @param hook An instance of a subclass of Hook defining its run method.<br>
   *   The object must be alive as long as the binding is active. A null value<br>
   *   can be passed to disconnect the current one.<br>
   * <br>
   * @return Whether this call overwrites a previous binding.
   */
  public static boolean connectRlHook(String name, Hook hook) {
    return maudeJNI.connectRlHook(name, Hook.getCPtr(hook), hook);
  }

}
