/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public interface maudeConstants {
  public final static int UNBOUNDED = maudeJNI.UNBOUNDED_get();
  public final static String MAUDE_VERSION = maudeJNI.MAUDE_VERSION_get();
}
