/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A sort membership axiom.
 */
public class MembershipAxiom extends ModuleItem {
  private transient long swigCPtr;

  protected MembershipAxiom(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.MembershipAxiom_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MembershipAxiom obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MembershipAxiom obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_MembershipAxiom(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the term of the membership axiom.
   */
  public Term getLhs() {
    long cPtr = maudeJNI.MembershipAxiom_getLhs(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the sort of the membership axiom.
   */
  public Sort getSort() {
    long cPtr = maudeJNI.MembershipAxiom_getSort(swigCPtr, this);
    return (cPtr == 0) ? null : new Sort(cPtr, true);
  }

  /**
   * Get the condition of the membership axiom.
   */
  public Condition getCondition() {
    return new Condition(maudeJNI.MembershipAxiom_getCondition(swigCPtr, this), false);
  }

  /**
   * Whether the membership axiom has the <code>nonexec</code> attribute.
   */
  public boolean isNonexec() {
    return maudeJNI.MembershipAxiom_isNonexec(swigCPtr, this);
  }

  /**
   * Get the label attribute.
   */
  public String getLabel() {
    return maudeJNI.MembershipAxiom_getLabel(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.MembershipAxiom_toString(swigCPtr, this);
  }

  /**
   * Get the free text <code>metadata</code> attribute of this statement.
   */
  public String getMetadata() {
    return maudeJNI.MembershipAxiom_getMetadata(swigCPtr, this);
  }

  /**
   * Get the line number information for this item as formatted by Maude.<br>
   * <br>
   * The format of the string is usually <code>filename, line line (module)</code><br>
   * where the second <code>line</code> is the integral line number, and <code>module</code> is<br>
   * the module type and name where this item was originally defined. The<br>
   * <code>filename</code> may be an actual quoted filename or some special name<br>
   * between angle brackets.
   */
  public String getLineNumber() {
    return maudeJNI.MembershipAxiom_getLineNumber(swigCPtr, this);
  }

  /**
   * Get the hash value of the membership axiom.
   */
  public long hash() {
    return maudeJNI.MembershipAxiom_hash(swigCPtr, this);
  }

  /**
   * Check whether two membership axiom are the same.
   */
  public boolean equal(MembershipAxiom other) {
    return maudeJNI.MembershipAxiom_equal(swigCPtr, this, MembershipAxiom.getCPtr(other), other);
  }

}
