/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Result of LTL model checking.
 */
public class ModelCheckResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModelCheckResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModelCheckResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ModelCheckResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_ModelCheckResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  Whether the property holds.
   */
  public boolean getHolds() {
    return maudeJNI.ModelCheckResult_holds_get(swigCPtr, this);
  }

  /**
   *  The counterexample path to the cycle.
   */
  public IntVector getLeadIn() {
    long cPtr = maudeJNI.ModelCheckResult_leadIn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntVector(cPtr, false);
  }

  /**
   *  The counterexample cycle.
   */
  public IntVector getCycle() {
    long cPtr = maudeJNI.ModelCheckResult_cycle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntVector(cPtr, false);
  }

  /**
   *  Number of states in the Büchi automaton.
   */
  public int getNrBuchiStates() {
    return maudeJNI.ModelCheckResult_nrBuchiStates_get(swigCPtr, this);
  }

  public ModelCheckResult() {
    this(maudeJNI.new_ModelCheckResult(), true);
  }

}
