/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A Maude module.
 */
public class Module {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Module(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Module obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Module obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Module(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Get the module type.<br>
   * <br>
   * This allows distinguishing modules from theories, and the<br>
   * functional, system and strategy variants within them.
   */
  public Module.ModuleType getModuleType() {
    return Module.ModuleType.swigToEnum(maudeJNI.Module_getModuleType(swigCPtr, this));
  }

  /**
   * Get the sorts declared in the module.
   */
  public SortVector getSorts() {
    return new SortVector(maudeJNI.Module_getSorts(swigCPtr, this), false);
  }

  /**
   * Get the symbols declared in the module.
   */
  public SymbolVector getSymbols() {
    return new SymbolVector(maudeJNI.Module_getSymbols(swigCPtr, this), false);
  }

  /**
   * Get the kinds defined in the module.
   */
  public KindVector getKinds() {
    return new KindVector(maudeJNI.Module_getKinds(swigCPtr, this), false);
  }

  /**
   * Get the membership axioms defined in the module.
   */
  public SubsortVector getMembershipAxioms() {
    return new SubsortVector(maudeJNI.Module_getMembershipAxioms(swigCPtr, this), false);
  }

  /**
   * Get the equations defined in the module.
   */
  public EquationVector getEquations() {
    return new EquationVector(maudeJNI.Module_getEquations(swigCPtr, this), false);
  }

  /**
   * Get the rules defined in the module.
   */
  public RuleVector getRules() {
    return new RuleVector(maudeJNI.Module_getRules(swigCPtr, this), false);
  }

  /**
   * Get the strategies declared in the module.
   */
  public StratVector getStrategies() {
    return new StratVector(maudeJNI.Module_getStrategies(swigCPtr, this), false);
  }

  /**
   * Get the strategy definitions defined in the module.
   */
  public StratDefVector getStrategyDefinitions() {
    return new StratDefVector(maudeJNI.Module_getStrategyDefinitions(swigCPtr, this), false);
  }

  /**
   * Number of parameters of the parameterized module.
   */
  public int getNrParameters() {
    return maudeJNI.Module_getNrParameters(swigCPtr, this);
  }

  /**
   * Is this a parameterized module with free parameters?
   */
  public boolean hasFreeParameters() {
    return maudeJNI.Module_hasFreeParameters(swigCPtr, this);
  }

  /**
   * Number of sorts imported from other modules or parameters.
   */
  public int getNrImportedSorts() {
    return maudeJNI.Module_getNrImportedSorts(swigCPtr, this);
  }

  /**
   * Number of symbols imported from other modules or parameters.
   */
  public int getNrImportedSymbols() {
    return maudeJNI.Module_getNrImportedSymbols(swigCPtr, this);
  }

  /**
   * Number of strategies imported from other modules or parameters.
   */
  public int getNrImportedStrategies() {
    return maudeJNI.Module_getNrImportedStrategies(swigCPtr, this);
  }

  /**
   * Number of equations from this module.
   */
  public int getNrOriginalEquations() {
    return maudeJNI.Module_getNrOriginalEquations(swigCPtr, this);
  }

  /**
   * Number of rules from this module.
   */
  public int getNrOriginalRules() {
    return maudeJNI.Module_getNrOriginalRules(swigCPtr, this);
  }

  /**
   * Number of strategy definitions from this module.
   */
  public int getNrOriginalStrategyDefinitions() {
    return maudeJNI.Module_getNrOriginalStrategyDefinitions(swigCPtr, this);
  }

  /**
   * Get the theory of the given parameter.
   */
  public Module getParameterTheory(int index) {
    long cPtr = maudeJNI.Module_getParameterTheory(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Module(cPtr, true);
  }

  /**
   * Get the name of a module parameter.<br>
   * <br>
   * @param index Index of the parameter.
   */
  public String getParameterName(int index) {
    return maudeJNI.Module_getParameterName(swigCPtr, this, index);
  }

  /**
   * Finds a sort by its name in the module.<br>
   * <br>
   * @param name The name of the sort.<br>
   * <br>
   * @return The sort or null if it does not exist.
   */
  public Sort findSort(String name) {
    long cPtr = maudeJNI.Module_findSort(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Sort(cPtr, true);
  }

  /**
   * Find a symbol by its name and signature in the module.<br>
   * <br>
   * @param name The name of the sort.<br>
   * @param domainKinds Kinds of the symbol domain.<br>
   * @param rangeKind Range kind of the symbol.<br>
   * <br>
   * @return The symbol or null if it does not exist.
   */
  public Symbol findSymbol(String name, KindVector domainKinds, Kind rangeKind) {
    long cPtr = maudeJNI.Module_findSymbol(swigCPtr, this, name, KindVector.getCPtr(domainKinds), domainKinds, Kind.getCPtr(rangeKind), rangeKind);
    return (cPtr == 0) ? null : new Symbol(cPtr, true);
  }

  /**
   * Parse a term.<br>
   * <br>
   * @param bubble Tokenized term.<br>
   * @param kind Restrict parsing to terms of the given kind.
   */
  public Term parseTerm(TokenVector bubble, Kind kind) {
    long cPtr = maudeJNI.Module_parseTerm__SWIG_0(swigCPtr, this, TokenVector.getCPtr(bubble), bubble, Kind.getCPtr(kind), kind);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Parse a term.<br>
   * <br>
   * @param bubble Tokenized term.<br>
   * 
   */
  public Term parseTerm(TokenVector bubble) {
    long cPtr = maudeJNI.Module_parseTerm__SWIG_1(swigCPtr, this, TokenVector.getCPtr(bubble), bubble);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Parse a term.<br>
   * <br>
   * @param term_str A term represented as a string.<br>
   * @param kind Restrict parsing to terms of the given kind.<br>
   * @param vars Variables that may appear without explicit type<br>
   * annotation in the strategy.
   */
  public Term parseTerm(String term_str, Kind kind, TermVector vars) {
    long cPtr = maudeJNI.Module_parseTerm__SWIG_2(swigCPtr, this, term_str, Kind.getCPtr(kind), kind, TermVector.getCPtr(vars), vars);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Parse a term.<br>
   * <br>
   * @param term_str A term represented as a string.<br>
   * @param kind Restrict parsing to terms of the given kind.<br>
   * 
   */
  public Term parseTerm(String term_str, Kind kind) {
    long cPtr = maudeJNI.Module_parseTerm__SWIG_3(swigCPtr, this, term_str, Kind.getCPtr(kind), kind);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Parse a term.<br>
   * <br>
   * @param term_str A term represented as a string.<br>
   * <br>
   * 
   */
  public Term parseTerm(String term_str) {
    long cPtr = maudeJNI.Module_parseTerm__SWIG_4(swigCPtr, this, term_str);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Parse a strategy expression.<br>
   * <br>
   * <br>
   * @param vars Variables that may appear without explicit type<br>
   * annotation in the strategy.
   */
  public StrategyExpression parseStrategy(String strat_str, TermVector vars) {
    long cPtr = maudeJNI.Module_parseStrategy__SWIG_0(swigCPtr, this, strat_str, TermVector.getCPtr(vars), vars);
    return (cPtr == 0) ? null : new StrategyExpression(cPtr, true);
  }

  /**
   * Parse a strategy expression.<br>
   * <br>
   * <br>
   * 
   */
  public StrategyExpression parseStrategy(String strat_str) {
    long cPtr = maudeJNI.Module_parseStrategy__SWIG_1(swigCPtr, this, strat_str);
    return (cPtr == 0) ? null : new StrategyExpression(cPtr, true);
  }

  /**
   * Get a term in this module from its metarepresentation<br>
   * in (possibly) another module.<br>
   * <br>
   * @param term The metarepresentation of a term, that is,<br>
   * a valid element of the <code>Term</code> sort in <code>META-TERM</code>.<br>
   * This term must belong to a module where the <code>META-LEVEL</code><br>
   * module is included. The term will be reduced.<br>
   * <br>
   * @return The term or null if the metarepresentation was<br>
   * not valid.
   */
  public Term downTerm(Term term) {
    long cPtr = maudeJNI.Module_downTerm(swigCPtr, this, Term.getCPtr(term), term);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get a strategy expression in this module from its<br>
   * metarepresentation in (possibly) another module.<br>
   * <br>
   * @param term The metarepresentation of a strategy, that is,<br>
   * a valid element of the <code>Strategy</code> sort in <code>META-STRATEGY</code>.<br>
   * This term must belong to a module where the <code>META-LEVEL</code><br>
   * module is included. The term will be reduced.<br>
   * <br>
   * @return The strategy expression or null if the<br>
   * metarepresentation was not valid.
   */
  public StrategyExpression downStrategy(Term term) {
    long cPtr = maudeJNI.Module_downStrategy(swigCPtr, this, Term.getCPtr(term), term);
    return (cPtr == 0) ? null : new StrategyExpression(cPtr, true);
  }

  /**
   * Get the metarepresentation in this module of a term<br>
   * in (possibly) another module. This module must contain<br>
   * <code>META-LEVEL</code>.<br>
   * <br>
   * @param term Any term.<br>
   * <br>
   * @return The metarepresentation term or null.
   */
  public Term upTerm(Term term) {
    long cPtr = maudeJNI.Module_upTerm(swigCPtr, this, Term.getCPtr(term), term);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the metarepresentation in this module of a strategy<br>
   * expression in (possibly) another module. This module must<br>
   * contain <code>META-LEVEL</code>.<br>
   * <br>
   * @param expr Any strategy expression.<br>
   * <br>
   * @return The metarepresented strategy or null.
   */
  public Term upStrategy(StrategyExpression expr) {
    long cPtr = maudeJNI.Module_upStrategy(swigCPtr, this, StrategyExpression.getCPtr(expr), expr);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Solves the given unification problem.<br>
   * <br>
   * @param problem A list of pairs of terms to be unified.<br>
   * @param irredundant Whether to compute a minimal set of unifiers.<br>
   * <br>
   * @return An object to iterate through unifiers.
   */
  public UnificationProblem unify(TermPairVector problem, boolean irredundant) {
    long cPtr = maudeJNI.Module_unify__SWIG_0(swigCPtr, this, TermPairVector.getCPtr(problem), problem, irredundant);
    return (cPtr == 0) ? null : new UnificationProblem(cPtr, true);
  }

  /**
   * Solves the given unification problem.<br>
   * <br>
   * @param problem A list of pairs of terms to be unified.<br>
   * <br>
   * <br>
   * @return An object to iterate through unifiers.
   */
  public UnificationProblem unify(TermPairVector problem) {
    long cPtr = maudeJNI.Module_unify__SWIG_1(swigCPtr, this, TermPairVector.getCPtr(problem), problem);
    return (cPtr == 0) ? null : new UnificationProblem(cPtr, true);
  }

  /**
   * Solves the given unification problem using variants.<br>
   * <br>
   * @param problem A list of pairs of terms to be unified.<br>
   * @param irreducible Irreducible terms.<br>
   * @param filtered Whether to compute a minimal set of unifiers.<br>
   * <br>
   * @return An object to iterate through unifiers.
   */
  public VariantUnifierSearch variant_unify(TermPairVector problem, TermVector irreducible, boolean filtered) {
    long cPtr = maudeJNI.Module_variant_unify__SWIG_0(swigCPtr, this, TermPairVector.getCPtr(problem), problem, TermVector.getCPtr(irreducible), irreducible, filtered);
    return (cPtr == 0) ? null : new VariantUnifierSearch(cPtr, true);
  }

  /**
   * Solves the given unification problem using variants.<br>
   * <br>
   * @param problem A list of pairs of terms to be unified.<br>
   * @param irreducible Irreducible terms.<br>
   * <br>
   * <br>
   * @return An object to iterate through unifiers.
   */
  public VariantUnifierSearch variant_unify(TermPairVector problem, TermVector irreducible) {
    long cPtr = maudeJNI.Module_variant_unify__SWIG_1(swigCPtr, this, TermPairVector.getCPtr(problem), problem, TermVector.getCPtr(irreducible), irreducible);
    return (cPtr == 0) ? null : new VariantUnifierSearch(cPtr, true);
  }

  /**
   * Solves the given unification problem using variants.<br>
   * <br>
   * @param problem A list of pairs of terms to be unified.<br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through unifiers.
   */
  public VariantUnifierSearch variant_unify(TermPairVector problem) {
    long cPtr = maudeJNI.Module_variant_unify__SWIG_2(swigCPtr, this, TermPairVector.getCPtr(problem), problem);
    return (cPtr == 0) ? null : new VariantUnifierSearch(cPtr, true);
  }

  /**
   * Computes a complete set of order-sorted matches modulo the equations<br>
   * declared with the variant attribute (which must satisfy the finite<br>
   * variant property) plus the (supported) equational axioms in the<br>
   * given module.<br>
   * <br>
   * @param problem A list of pairs of terms to be matched.<br>
   * @param irreducible Irreducible terms.<br>
   * <br>
   * @return An object to iterate through unifiers.
   */
  public VariantUnifierSearch variant_match(TermPairVector problem, TermVector irreducible) {
    long cPtr = maudeJNI.Module_variant_match__SWIG_0(swigCPtr, this, TermPairVector.getCPtr(problem), problem, TermVector.getCPtr(irreducible), irreducible);
    return (cPtr == 0) ? null : new VariantUnifierSearch(cPtr, true);
  }

  /**
   * Computes a complete set of order-sorted matches modulo the equations<br>
   * declared with the variant attribute (which must satisfy the finite<br>
   * variant property) plus the (supported) equational axioms in the<br>
   * given module.<br>
   * <br>
   * @param problem A list of pairs of terms to be matched.<br>
   * <br>
   * <br>
   * @return An object to iterate through unifiers.
   */
  public VariantUnifierSearch variant_match(TermPairVector problem) {
    long cPtr = maudeJNI.Module_variant_match__SWIG_1(swigCPtr, this, TermPairVector.getCPtr(problem), problem);
    return (cPtr == 0) ? null : new VariantUnifierSearch(cPtr, true);
  }

  /**
   * Narrowing-based search of terms that unify with the given target<br>
   * with multiple initial states.<br>
   * <br>
   * @param subject Subject terms where to start the search.<br>
   * @param type Type of the search (number of steps).<br>
   * @param target Term that found states must unify with.<br>
   * @param depth Depth bound (<code>-1</code> for unbounded)<br>
   * @param flags Narrowing search flags (<code>fold</code>, <code>vfold</code>, <code>path</code>, <code>delay</code>, or <code>filter</code> flag).
   */
  public NarrowingSequenceSearch vu_narrow(TermVector subject, SearchType type, Term target, int depth, int flags) {
    long cPtr = maudeJNI.Module_vu_narrow__SWIG_0(swigCPtr, this, TermVector.getCPtr(subject), subject, type.swigValue(), Term.getCPtr(target), target, depth, flags);
    return (cPtr == 0) ? null : new NarrowingSequenceSearch(cPtr, true);
  }

  /**
   * Narrowing-based search of terms that unify with the given target<br>
   * with multiple initial states.<br>
   * <br>
   * @param subject Subject terms where to start the search.<br>
   * @param type Type of the search (number of steps).<br>
   * @param target Term that found states must unify with.<br>
   * @param depth Depth bound (<code>-1</code> for unbounded)<br>
   * 
   */
  public NarrowingSequenceSearch vu_narrow(TermVector subject, SearchType type, Term target, int depth) {
    long cPtr = maudeJNI.Module_vu_narrow__SWIG_1(swigCPtr, this, TermVector.getCPtr(subject), subject, type.swigValue(), Term.getCPtr(target), target, depth);
    return (cPtr == 0) ? null : new NarrowingSequenceSearch(cPtr, true);
  }

  /**
   * Narrowing-based search of terms that unify with the given target<br>
   * with multiple initial states.<br>
   * <br>
   * @param subject Subject terms where to start the search.<br>
   * @param type Type of the search (number of steps).<br>
   * @param target Term that found states must unify with.<br>
   * <br>
   * 
   */
  public NarrowingSequenceSearch vu_narrow(TermVector subject, SearchType type, Term target) {
    long cPtr = maudeJNI.Module_vu_narrow__SWIG_2(swigCPtr, this, TermVector.getCPtr(subject), subject, type.swigValue(), Term.getCPtr(target), target);
    return (cPtr == 0) ? null : new NarrowingSequenceSearch(cPtr, true);
  }

  /**
   * Obtain the LaTeX representation of this module.<br>
   * <br>
   * @param all Whether to show all statements by transitivity.
   */
  public String toLatex(boolean all) {
    return maudeJNI.Module_toLatex__SWIG_0(swigCPtr, this, all);
  }

  /**
   * Obtain the LaTeX representation of this module.<br>
   * <br>
   * 
   */
  public String toLatex() {
    return maudeJNI.Module_toLatex__SWIG_1(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.Module_toString(swigCPtr, this);
  }

  /**
   * Module or theory type (function, system or strategy).
   */
  public final static class ModuleType {
    /**
     *  Functional module (<code>fmod</code>)
     */
    public final static Module.ModuleType FUNCTIONAL_MODULE = new Module.ModuleType("FUNCTIONAL_MODULE", maudeJNI.Module_FUNCTIONAL_MODULE_get());
    /**
     *  System module (<code>mod</code>)
     */
    public final static Module.ModuleType SYSTEM_MODULE = new Module.ModuleType("SYSTEM_MODULE", maudeJNI.Module_SYSTEM_MODULE_get());
    /**
     *  Strategy module (<code>smod</code>)
     */
    public final static Module.ModuleType STRATEGY_MODULE = new Module.ModuleType("STRATEGY_MODULE", maudeJNI.Module_STRATEGY_MODULE_get());
    /**
     *  Functional theory (<code>fth</code>)
     */
    public final static Module.ModuleType FUNCTIONAL_THEORY = new Module.ModuleType("FUNCTIONAL_THEORY", maudeJNI.Module_FUNCTIONAL_THEORY_get());
    /**
     *  System theory (<code>th</code>)
     */
    public final static Module.ModuleType SYSTEM_THEORY = new Module.ModuleType("SYSTEM_THEORY", maudeJNI.Module_SYSTEM_THEORY_get());
    /**
     *  Strategy theory (<code>sth</code>)
     */
    public final static Module.ModuleType STRATEGY_THEORY = new Module.ModuleType("STRATEGY_THEORY", maudeJNI.Module_STRATEGY_THEORY_get());
    /**
     *  Object-oriented module (<code>omod</code>)
     */
    public final static Module.ModuleType OBJECT_ORIENTED_MODULE = new Module.ModuleType("OBJECT_ORIENTED_MODULE", maudeJNI.Module_OBJECT_ORIENTED_MODULE_get());
    /**
     *  Object-oriented theory (<code>oth</code>)
     */
    public final static Module.ModuleType OBJECT_ORIENTED_THEORY = new Module.ModuleType("OBJECT_ORIENTED_THEORY", maudeJNI.Module_OBJECT_ORIENTED_THEORY_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ModuleType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ModuleType.class + " with value " + swigValue);
    }

    private ModuleType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ModuleType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ModuleType(String swigName, ModuleType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ModuleType[] swigValues = { FUNCTIONAL_MODULE, SYSTEM_MODULE, STRATEGY_MODULE, FUNCTIONAL_THEORY, SYSTEM_THEORY, STRATEGY_THEORY, OBJECT_ORIENTED_MODULE, OBJECT_ORIENTED_THEORY };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
