/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class ModuleHeaderVector extends java.util.AbstractList<ModuleHeader> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModuleHeaderVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModuleHeaderVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ModuleHeaderVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_ModuleHeaderVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModuleHeaderVector(ModuleHeader[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ModuleHeader element : initialElements) {
      add(element);
    }
  }

  public ModuleHeaderVector(Iterable<ModuleHeader> initialElements) {
    this();
    for (ModuleHeader element : initialElements) {
      add(element);
    }
  }

  public ModuleHeader get(int index) {
    return doGet(index);
  }

  public ModuleHeader set(int index, ModuleHeader e) {
    return doSet(index, e);
  }

  public boolean add(ModuleHeader e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ModuleHeader e) {
    modCount++;
    doAdd(index, e);
  }

  public ModuleHeader remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public ModuleHeaderVector() {
    this(maudeJNI.new_ModuleHeaderVector__SWIG_0(), true);
  }

  public ModuleHeaderVector(ModuleHeaderVector other) {
    this(maudeJNI.new_ModuleHeaderVector__SWIG_1(ModuleHeaderVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return maudeJNI.ModuleHeaderVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    maudeJNI.ModuleHeaderVector_clear(swigCPtr, this);
  }

  public ModuleHeaderVector(int count, ModuleHeader value) {
    this(maudeJNI.new_ModuleHeaderVector__SWIG_2(count, ModuleHeader.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return maudeJNI.ModuleHeaderVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    maudeJNI.ModuleHeaderVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return maudeJNI.ModuleHeaderVector_doSize(swigCPtr, this);
  }

  private void doAdd(ModuleHeader x) {
    maudeJNI.ModuleHeaderVector_doAdd__SWIG_0(swigCPtr, this, ModuleHeader.getCPtr(x), x);
  }

  private void doAdd(int index, ModuleHeader x) {
    maudeJNI.ModuleHeaderVector_doAdd__SWIG_1(swigCPtr, this, index, ModuleHeader.getCPtr(x), x);
  }

  private ModuleHeader doRemove(int index) {
    return new ModuleHeader(maudeJNI.ModuleHeaderVector_doRemove(swigCPtr, this, index), true);
  }

  private ModuleHeader doGet(int index) {
    return new ModuleHeader(maudeJNI.ModuleHeaderVector_doGet(swigCPtr, this, index), false);
  }

  private ModuleHeader doSet(int index, ModuleHeader val) {
    return new ModuleHeader(maudeJNI.ModuleHeaderVector_doSet(swigCPtr, this, index, ModuleHeader.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    maudeJNI.ModuleHeaderVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
