/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Module header information.
 */
public class ModuleHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModuleHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModuleHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ModuleHeader obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_ModuleHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  Type of the module (see Module class)
   */
  public Module.ModuleType getType() {
    return Module.ModuleType.swigToEnum(maudeJNI.ModuleHeader_type_get(swigCPtr, this));
  }

  /**
   *  Name of the module
   */
  public String getName() {
    return maudeJNI.ModuleHeader_name_get(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.ModuleHeader_toString(swigCPtr, this);
  }

  public ModuleHeader() {
    this(maudeJNI.new_ModuleHeader(), true);
  }

}
