/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

		import java.util.Iterator;
		import java.util.NoSuchElementException;
	
/**
 * An iterator through narrowing solutions.
 */
public class NarrowingSequenceSearch implements Iterable<Term>, Iterator<Term> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NarrowingSequenceSearch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NarrowingSequenceSearch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NarrowingSequenceSearch obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_NarrowingSequenceSearch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

		private transient Term last = null;
		private transient boolean advanced = false;

		public Iterator<Term> iterator() {
			return this;
		}

		public boolean hasNext() {
			if (!advanced) {
				last = __next();
				advanced = true;
			}
			return last != null;
		}

		public Term next() {
			if (!advanced)
				hasNext();
			if (last == null)
				throw new NoSuchElementException("no more solutions");
			advanced = false;
			return last;
		}
	
  /**
   * Whether some solutions may have been missed due to incomplete unification algorithms.
   */
  public boolean isIncomplete() {
    return maudeJNI.NarrowingSequenceSearch_isIncomplete(swigCPtr, this);
  }

  /**
   * Get the parent state.<br>
   * <br>
   * @param stateNr The number of state in the search graph.<br>
   * <br>
   * @return The number of the parent or -1 for the root.
   */
  public int getStateParent(int stateNr) {
    return maudeJNI.NarrowingSequenceSearch_getStateParent(swigCPtr, this, stateNr);
  }

  /**
   * Get the next solution of the narrowing search.
   */
  public Term __next() {
    long cPtr = maudeJNI.NarrowingSequenceSearch___next(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the accumulated substitution.
   */
  public Substitution getSubstitution() {
    long cPtr = maudeJNI.NarrowingSequenceSearch_getSubstitution(swigCPtr, this);
    return (cPtr == 0) ? null : new Substitution(cPtr, true);
  }

  /**
   * Get the variant unifier.
   */
  public Substitution getUnifier() {
    long cPtr = maudeJNI.NarrowingSequenceSearch_getUnifier(swigCPtr, this);
    return (cPtr == 0) ? null : new Substitution(cPtr, true);
  }

  /**
   * Get the frontier states.
   */
  public TermVector getFrontierStates() {
    return new TermVector(maudeJNI.NarrowingSequenceSearch_getFrontierStates(swigCPtr, this), true);
  }

  /**
   * Get the most general states.
   */
  public TermVector getMostGeneralStates() {
    return new TermVector(maudeJNI.NarrowingSequenceSearch_getMostGeneralStates(swigCPtr, this), true);
  }

}
