/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * NarrowingFlags
 */
public final class NarrowingFlags {
  /**
   *  Whether to activate folding (<code>fold</code> option or <code>fvu-narrow</code> command).
   */
  public final static NarrowingFlags FOLD = new NarrowingFlags("FOLD", maudeJNI.FOLD_get());
  /**
   *  Whether to activate variant folding (<code>vfold</code> option).
   */
  public final static NarrowingFlags VFOLD = new NarrowingFlags("VFOLD", maudeJNI.VFOLD_get());
  /**
   *  Whether to allow for narrowing trace reconstruction (expensive).
   */
  public final static NarrowingFlags PATH = new NarrowingFlags("PATH", maudeJNI.PATH_get());
  /**
   *  Whether variant unifiers are filtered before using the first one for narrowing (<code>delay</code> option in the command).
   */
  public final static NarrowingFlags DELAY = new NarrowingFlags("DELAY", maudeJNI.DELAY_get());
  /**
   *  Whether to activate filtered variant unification (<code>filter</code> option in the command).
   */
  public final static NarrowingFlags FILTER = new NarrowingFlags("FILTER", maudeJNI.FILTER_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NarrowingFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NarrowingFlags.class + " with value " + swigValue);
  }

  private NarrowingFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NarrowingFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NarrowingFlags(String swigName, NarrowingFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NarrowingFlags[] swigValues = { FOLD, VFOLD, PATH, DELAY, FILTER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

