/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Syntactical operator declaration.
 */
public class OpDeclaration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpDeclaration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpDeclaration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OpDeclaration obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_OpDeclaration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Get domain and range sorts (range is last).
   */
  public SortVector getDomainAndRange() {
    return new SortVector(maudeJNI.OpDeclaration_getDomainAndRange(swigCPtr, this), false);
  }

  /**
   * Is the declared operator marked as a data constructor?
   */
  public boolean isConstructor() {
    return maudeJNI.OpDeclaration_isConstructor(swigCPtr, this);
  }

  public OpDeclaration() {
    this(maudeJNI.new_OpDeclaration(), true);
  }

}
