/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Print flags.
 */
public final class PrintFlags {
  /**
   *  respect concealed argument lists
   */
  public final static PrintFlags PRINT_CONCEAL = new PrintFlags("PRINT_CONCEAL", maudeJNI.PRINT_CONCEAL_get());
  /**
   *  respect format attribute
   */
  public final static PrintFlags PRINT_FORMAT = new PrintFlags("PRINT_FORMAT", maudeJNI.PRINT_FORMAT_get());
  /**
   *  mixfix notation
   */
  public final static PrintFlags PRINT_MIXFIX = new PrintFlags("PRINT_MIXFIX", maudeJNI.PRINT_MIXFIX_get());
  /**
   *  maximal parens
   */
  public final static PrintFlags PRINT_WITH_PARENS = new PrintFlags("PRINT_WITH_PARENS", maudeJNI.PRINT_WITH_PARENS_get());
  /**
   *  dag node coloring based on ctor/reduced status
   */
  public final static PrintFlags PRINT_COLOR = new PrintFlags("PRINT_COLOR", maudeJNI.PRINT_COLOR_get());
  /**
   *  (c).s for every constant c
   */
  public final static PrintFlags PRINT_DISAMBIG_CONST = new PrintFlags("PRINT_DISAMBIG_CONST", maudeJNI.PRINT_DISAMBIG_CONST_get());
  /**
   *  for variables
   */
  public final static PrintFlags PRINT_WITH_ALIASES = new PrintFlags("PRINT_WITH_ALIASES", maudeJNI.PRINT_WITH_ALIASES_get());
  /**
   *  for assoc symbols
   */
  public final static PrintFlags PRINT_FLAT = new PrintFlags("PRINT_FLAT", maudeJNI.PRINT_FLAT_get());
  /**
   *  for nats &amp; ints
   */
  public final static PrintFlags PRINT_NUMBER = new PrintFlags("PRINT_NUMBER", maudeJNI.PRINT_NUMBER_get());
  /**
   *  for rats
   */
  public final static PrintFlags PRINT_RAT = new PrintFlags("PRINT_RAT", maudeJNI.PRINT_RAT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PrintFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PrintFlags.class + " with value " + swigValue);
  }

  private PrintFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PrintFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PrintFlags(String swigName, PrintFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PrintFlags[] swigValues = { PRINT_CONCEAL, PRINT_FORMAT, PRINT_MIXFIX, PRINT_WITH_PARENS, PRINT_COLOR, PRINT_DISAMBIG_CONST, PRINT_WITH_ALIASES, PRINT_FLAT, PRINT_NUMBER, PRINT_RAT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

