/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Complete rewriting graph from an initial state.
 */
public class RewriteGraph {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RewriteGraph(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RewriteGraph obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RewriteGraph obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_RewriteGraph(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a state transition graph.<br>
   * <br>
   * @param term Initial state term (it will be reduced).
   */
  public RewriteGraph(Term term) {
    this(maudeJNI.new_RewriteGraph(Term.getCPtr(term), term), true);
  }

  /**
   * Get the term of the given state.<br>
   * <br>
   * @param stateNr A state number.
   */
  public Term getStateTerm(int stateNr) {
    long cPtr = maudeJNI.RewriteGraph_getStateTerm(swigCPtr, this, stateNr);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get a rule that connects two states.<br>
   * <br>
   * @param origin Origin state number.<br>
   * @param dest Destination state number.<br>
   * <br>
   * @return A rule that connects the two states or null if none.
   */
  public Rule getRule(int origin, int dest) {
    long cPtr = maudeJNI.RewriteGraph_getRule(swigCPtr, this, origin, dest);
    return (cPtr == 0) ? null : new Rule(cPtr, false);
  }

  /**
   * Get the number of rewrites used to generate this graph,<br>
   * including the evaluation of atomic propositions.
   */
  public int getNrRewrites() {
    return maudeJNI.RewriteGraph_getNrRewrites(swigCPtr, this);
  }

  /**
   * Model check a given LTL formula.<br>
   * <br>
   * @param formula Term of the <code>Formula</code> sort.<br>
   * <br>
   * @return The result of model checking.
   */
  public ModelCheckResult modelCheck(Term formula) {
    long cPtr = maudeJNI.RewriteGraph_modelCheck(swigCPtr, this, Term.getCPtr(formula), formula);
    return (cPtr == 0) ? null : new ModelCheckResult(cPtr, true);
  }

  /**
   * Get the number of states in the graph.
   */
  public int getNrStates() {
    return maudeJNI.RewriteGraph_getNrStates(swigCPtr, this);
  }

  /**
   * List the successors of a state in the graph.<br>
   * <br>
   * @param stateNr A state number.<br>
   * @param index A child index (from zero).<br>
   * <br>
   * @return The state number of a successor or -1.
   */
  public int getNextState(int stateNr, int index) {
    return maudeJNI.RewriteGraph_getNextState(swigCPtr, this, stateNr, index);
  }

  /**
   * Get the (one) parent of a given state.<br>
   * <br>
   * @param stateNr A state number.<br>
   * <br>
   * @return The state number of the parent or -1.
   */
  public int getStateParent(int stateNr) {
    return maudeJNI.RewriteGraph_getStateParent(swigCPtr, this, stateNr);
  }

}
