/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A named rewriting strategy.
 */
public class RewriteStrategy extends ModuleItem {
  private transient long swigCPtr;

  protected RewriteStrategy(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.RewriteStrategy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RewriteStrategy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RewriteStrategy obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_RewriteStrategy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the argument domain.
   */
  public SortVector getDomain() {
    return new SortVector(maudeJNI.RewriteStrategy_getDomain(swigCPtr, this), false);
  }

  /**
   * Get the sort to which the strategy is intended to be applied.
   */
  public Sort getSubjectSort() {
    long cPtr = maudeJNI.RewriteStrategy_getSubjectSort(swigCPtr, this);
    return (cPtr == 0) ? null : new Sort(cPtr, true);
  }

  /**
   * Get the definitions for this strategy.
   */
  public StratDefVector getDefinitions() {
    return new StratDefVector(maudeJNI.RewriteStrategy_getDefinitions(swigCPtr, this), false);
  }

  /**
   * Get the number of arguments of the strategy.
   */
  public int arity() {
    return maudeJNI.RewriteStrategy_arity(swigCPtr, this);
  }

  public String getName() {
    return maudeJNI.RewriteStrategy_getName(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.RewriteStrategy_toString(swigCPtr, this);
  }

  /**
   * Get the free text <code>metadata</code> attribute of this statement.
   */
  public String getMetadata() {
    return maudeJNI.RewriteStrategy_getMetadata(swigCPtr, this);
  }

  /**
   * Get the line number information for this item as formatted by Maude.<br>
   * <br>
   * The format of the string is usually <code>filename, line line (module)</code><br>
   * where the second <code>line</code> is the integral line number, and <code>module</code> is<br>
   * the module type and name where this item was originally defined. The<br>
   * <code>filename</code> may be an actual quoted filename or some special name<br>
   * between angle brackets.
   */
  public String getLineNumber() {
    return maudeJNI.RewriteStrategy_getLineNumber(swigCPtr, this);
  }

  /**
   * Get the hash value of the strategy.
   */
  public long hash() {
    return maudeJNI.RewriteStrategy_hash(swigCPtr, this);
  }

  /**
   * Check whether two strategy are the same.
   */
  public boolean equal(RewriteStrategy other) {
    return maudeJNI.RewriteStrategy_equal(swigCPtr, this, RewriteStrategy.getCPtr(other), other);
  }

}
