/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

		import java.util.Iterator;
		import java.util.NoSuchElementException;
	
/**
 * An iterator through the solutions of a search.
 */
public class RewriteSequenceSearch implements Iterable<Term>, Iterator<Term> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RewriteSequenceSearch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RewriteSequenceSearch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RewriteSequenceSearch obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_RewriteSequenceSearch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

		private transient Term last = null;
		private transient boolean advanced = false;

		public Iterator<Term> iterator() {
			return this;
		}

		public boolean hasNext() {
			if (!advanced) {
				last = __next();
				advanced = true;
			}
			return last != null;
		}

		public Term next() {
			if (!advanced)
				hasNext();
			if (last == null)
				throw new NoSuchElementException("no more solutions");
			advanced = false;
			return last;
		}
	
  /**
   * Get the number of rewrites until this term has been found.
   */
  public int getRewriteCount() {
    return maudeJNI.RewriteSequenceSearch_getRewriteCount(swigCPtr, this);
  }

  /**
   * Get the matching substitution of the solution into the pattern.
   */
  public Substitution getSubstitution() {
    long cPtr = maudeJNI.RewriteSequenceSearch_getSubstitution(swigCPtr, this);
    return (cPtr == 0) ? null : new Substitution(cPtr, true);
  }

  /**
   * Get the rule leading to the given state.<br>
   * <br>
   * @param stateNr The number of a state in the search graph<br>
   * or -1 for the current one.
   */
  public Rule getRule(int stateNr) {
    long cPtr = maudeJNI.RewriteSequenceSearch_getRule__SWIG_0(swigCPtr, this, stateNr);
    return (cPtr == 0) ? null : new Rule(cPtr, false);
  }

  /**
   * Get the rule leading to the given state.<br>
   * <br>
   * 
   */
  public Rule getRule() {
    long cPtr = maudeJNI.RewriteSequenceSearch_getRule__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Rule(cPtr, false);
  }

  /**
   * Get the term of a given state.<br>
   * <br>
   * @param stateNr The number of a state in the search graph.
   */
  public Term getStateTerm(int stateNr) {
    long cPtr = maudeJNI.RewriteSequenceSearch_getStateTerm(swigCPtr, this, stateNr);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the next match.<br>
   * <br>
   * @return A term or a null pointer if there is no more matches.
   */
  public Term __next() {
    long cPtr = maudeJNI.RewriteSequenceSearch___next(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get an internal state number that allows reconstructing <br>
   * the path to this term.
   */
  public int getStateNr() {
    return maudeJNI.RewriteSequenceSearch_getStateNr(swigCPtr, this);
  }

  /**
   * Get the parent state.<br>
   * <br>
   * @param stateNr The number of a state in the search graph.<br>
   * <br>
   * @return The number of the parent or -1 for the root.
   */
  public int getStateParent(int stateNr) {
    return maudeJNI.RewriteSequenceSearch_getStateParent(swigCPtr, this, stateNr);
  }

}
