/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Search types (number of steps).
 */
public final class SearchType {
  /**
   *  -&gt;1
   */
  public final static SearchType ONE_STEP = new SearchType("ONE_STEP");
  /**
   *  -&gt;+
   */
  public final static SearchType AT_LEAST_ONE_STEP = new SearchType("AT_LEAST_ONE_STEP");
  /**
   *  -&gt;*
   */
  public final static SearchType ANY_STEPS = new SearchType("ANY_STEPS");
  /**
   *  -&gt;!
   */
  public final static SearchType NORMAL_FORM = new SearchType("NORMAL_FORM");
  /**
   *  -&gt;#
   */
  public final static SearchType BRANCH = new SearchType("BRANCH");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SearchType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SearchType.class + " with value " + swigValue);
  }

  private SearchType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SearchType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SearchType(String swigName, SearchType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SearchType[] swigValues = { ONE_STEP, AT_LEAST_ONE_STEP, ANY_STEPS, NORMAL_FORM, BRANCH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

