/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A sort test <code>t : s</code> condition.
 */
public class SortTestCondition extends ConditionFragment {
  private transient long swigCPtr;

  protected SortTestCondition(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.SortTestCondition_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SortTestCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SortTestCondition obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_SortTestCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SortTestCondition(Term lhs, Sort rhs) {
    this(maudeJNI.new_SortTestCondition(Term.getCPtr(lhs), lhs, Sort.getCPtr(rhs), rhs), true);
  }

  /**
   * Get the term of the sort test.
   */
  public Term getLhs() {
    long cPtr = maudeJNI.SortTestCondition_getLhs(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the sort of the sort test.
   */
  public Sort getSort() {
    long cPtr = maudeJNI.SortTestCondition_getSort(swigCPtr, this);
    return (cPtr == 0) ? null : new Sort(cPtr, true);
  }

  public String toString() {
    return maudeJNI.SortTestCondition_toString(swigCPtr, this);
  }

}
