/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A Maude sort.
 */
public class Sort extends ModuleItem {
  private transient long swigCPtr;

  protected Sort(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.Sort_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Sort obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Sort obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Sort(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the kind this sort belongs to.
   */
  public Kind kind() {
    long cPtr = maudeJNI.Sort_kind(swigCPtr, this);
    return (cPtr == 0) ? null : new Kind(cPtr, true);
  }

  /**
   * Get the subsorts of this sort.
   */
  public SortVector getSubsorts() {
    return new SortVector(maudeJNI.Sort_getSubsorts(swigCPtr, this), false);
  }

  /**
   * Get the supersorts of this sort.
   */
  public SortVector getSupersorts() {
    return new SortVector(maudeJNI.Sort_getSupersorts(swigCPtr, this), false);
  }

  /**
   * Check if this sort is a subsort of the given sort.<br>
   * <br>
   * @param rhs The right-hand side of the comparison.
   */
  public boolean leq(Sort rhs) {
    return maudeJNI.Sort_leq(swigCPtr, this, Sort.getCPtr(rhs), rhs);
  }

  public String toString() {
    return maudeJNI.Sort_toString(swigCPtr, this);
  }

  /**
   * Get the line number information for this item as formatted by Maude.<br>
   * <br>
   * The format of the string is usually <code>filename, line line (module)</code><br>
   * where the second <code>line</code> is the integral line number, and <code>module</code> is<br>
   * the module type and name where this item was originally defined. The<br>
   * <code>filename</code> may be an actual quoted filename or some special name<br>
   * between angle brackets.
   */
  public String getLineNumber() {
    return maudeJNI.Sort_getLineNumber(swigCPtr, this);
  }

  /**
   * Get the hash value of the sort.
   */
  public long hash() {
    return maudeJNI.Sort_hash(swigCPtr, this);
  }

  /**
   * Check whether two sort are the same.
   */
  public boolean equal(Sort other) {
    return maudeJNI.Sort_equal(swigCPtr, this, Sort.getCPtr(other), other);
  }

}
