/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Structure describing a transition in the graph.
 */
public class StrategyGraphTransition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StrategyGraphTransition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrategyGraphTransition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StrategyGraphTransition obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_StrategyGraphTransition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Get the transition type (rule application, opaque strategy,<br>
   * or solution).
   */
  public StrategyRewriteGraph.TransitionType getType() {
    return StrategyRewriteGraph.TransitionType.swigToEnum(maudeJNI.StrategyGraphTransition_getType(swigCPtr, this));
  }

  /**
   * Get the rule applied, in case the transition is a rule application.<br>
   * <br>
   * @return That rule or a null pointer if the transition is not<br>
   * a rule application.
   */
  public Rule getRule() {
    long cPtr = maudeJNI.StrategyGraphTransition_getRule(swigCPtr, this);
    return (cPtr == 0) ? null : new Rule(cPtr, false);
  }

  /**
   * Get the strategy executed, in case of an opaque transition.<br>
   * <br>
   * @return That strategy or a null pointer if the transition<br>
   * is not an opaque strategy.
   */
  public RewriteStrategy getStrategy() {
    long cPtr = maudeJNI.StrategyGraphTransition_getStrategy(swigCPtr, this);
    return (cPtr == 0) ? null : new RewriteStrategy(cPtr, false);
  }

  public String toString() {
    return maudeJNI.StrategyGraphTransition_toString(swigCPtr, this);
  }

}
