/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * An expression of the Maude strategy language.
 */
public class StrategyExpression {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StrategyExpression(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrategyExpression obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StrategyExpression obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_StrategyExpression(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Check whether two strategy expression are the same.<br>
   * <br>
   * Note: Not accurate (false negatives).
   */
  public boolean equal(StrategyExpression other) {
    return maudeJNI.StrategyExpression_equal(swigCPtr, this, StrategyExpression.getCPtr(other), other);
  }

  /**
   * Obtain the LaTeX representation of this strategy expression.
   */
  public String toLatex() {
    return maudeJNI.StrategyExpression_toLatex(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.StrategyExpression_toString(swigCPtr, this);
  }

}
