/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

		import java.util.Iterator;
		import java.util.NoSuchElementException;
	
/**
 * An iterator through the solutions of a strategy search.
 */
public class StrategicSearch implements Iterable<Term>, Iterator<Term> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StrategicSearch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrategicSearch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StrategicSearch obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_StrategicSearch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

		private transient Term last = null;
		private transient boolean advanced = false;

		public Iterator<Term> iterator() {
			return this;
		}

		public boolean hasNext() {
			if (!advanced) {
				last = __next();
				advanced = true;
			}
			return last != null;
		}

		public Term next() {
			if (!advanced)
				hasNext();
			if (last == null)
				throw new NoSuchElementException("no more solutions");
			advanced = false;
			return last;
		}
	
  /**
   * Get the number of rewrites until the solution has been found.
   */
  public int getRewriteCount() {
    return maudeJNI.StrategicSearch_getRewriteCount(swigCPtr, this);
  }

  /**
   * Get the next solution for the strategic search.<br>
   * <br>
   * @return That solution or null pointer if the end has<br>
   * been reached.
   */
  public Term __next() {
    long cPtr = maudeJNI.StrategicSearch___next(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

}
