/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A Maude strategy definition.
 */
public class StrategyDefinition extends ModuleItem {
  private transient long swigCPtr;

  protected StrategyDefinition(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.StrategyDefinition_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrategyDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StrategyDefinition obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_StrategyDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the left-hand side of the strategy definition as a term.
   */
  public Term getLhs() {
    long cPtr = maudeJNI.StrategyDefinition_getLhs(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the strategy definition.
   */
  public StrategyExpression getRhs() {
    long cPtr = maudeJNI.StrategyDefinition_getRhs(swigCPtr, this);
    return (cPtr == 0) ? null : new StrategyExpression(cPtr, false);
  }

  /**
   * Get the named strategy being defined.
   */
  public RewriteStrategy getStrategy() {
    long cPtr = maudeJNI.StrategyDefinition_getStrategy(swigCPtr, this);
    return (cPtr == 0) ? null : new RewriteStrategy(cPtr, false);
  }

  /**
   * Whether the strategy definition has the <code>nonexec</code> attribute.
   */
  public boolean isNonexec() {
    return maudeJNI.StrategyDefinition_isNonexec(swigCPtr, this);
  }

  /**
   * Whether the strategy definition has a condition.
   */
  public boolean hasCondition() {
    return maudeJNI.StrategyDefinition_hasCondition(swigCPtr, this);
  }

  /**
   * Get the condition of the strategy definition.
   */
  public Condition getCondition() {
    return new Condition(maudeJNI.StrategyDefinition_getCondition(swigCPtr, this), false);
  }

  /**
   * Get the label attribute.
   */
  public String getLabel() {
    return maudeJNI.StrategyDefinition_getLabel(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.StrategyDefinition_toString(swigCPtr, this);
  }

  /**
   * Get the free text <code>metadata</code> attribute of this statement.
   */
  public String getMetadata() {
    return maudeJNI.StrategyDefinition_getMetadata(swigCPtr, this);
  }

  /**
   * Get the line number information for this item as formatted by Maude.<br>
   * <br>
   * The format of the string is usually <code>filename, line line (module)</code><br>
   * where the second <code>line</code> is the integral line number, and <code>module</code> is<br>
   * the module type and name where this item was originally defined. The<br>
   * <code>filename</code> may be an actual quoted filename or some special name<br>
   * between angle brackets.
   */
  public String getLineNumber() {
    return maudeJNI.StrategyDefinition_getLineNumber(swigCPtr, this);
  }

  /**
   * Get the hash value of the strategy definition.
   */
  public long hash() {
    return maudeJNI.StrategyDefinition_hash(swigCPtr, this);
  }

  /**
   * Check whether two strategy definition are the same.
   */
  public boolean equal(StrategyDefinition other) {
    return maudeJNI.StrategyDefinition_equal(swigCPtr, this, StrategyDefinition.getCPtr(other), other);
  }

}
