/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Complete rewriting graph under the control of a strategy from an initial state.
 */
public class StrategyRewriteGraph {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StrategyRewriteGraph(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrategyRewriteGraph obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StrategyRewriteGraph obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_StrategyRewriteGraph(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a strategy transition graph.<br>
   * <br>
   * @param initial Initial state term (it will be reduced).<br>
   * @param strat A strategy expression.<br>
   * @param opaques A list of strategy names to be considered opaque.<br>
   * @param biased Whether the matchrews should be biased.
   */
  public StrategyRewriteGraph(Term initial, StrategyExpression strat, StringVector opaques, boolean biased) {
    this(maudeJNI.new_StrategyRewriteGraph__SWIG_0(Term.getCPtr(initial), initial, StrategyExpression.getCPtr(strat), strat, StringVector.getCPtr(opaques), opaques, biased), true);
  }

  /**
   * Construct a strategy transition graph.<br>
   * <br>
   * @param initial Initial state term (it will be reduced).<br>
   * @param strat A strategy expression.<br>
   * @param opaques A list of strategy names to be considered opaque.<br>
   * 
   */
  public StrategyRewriteGraph(Term initial, StrategyExpression strat, StringVector opaques) {
    this(maudeJNI.new_StrategyRewriteGraph__SWIG_1(Term.getCPtr(initial), initial, StrategyExpression.getCPtr(strat), strat, StringVector.getCPtr(opaques), opaques), true);
  }

  /**
   * Construct a strategy transition graph.<br>
   * <br>
   * @param initial Initial state term (it will be reduced).<br>
   * @param strat A strategy expression.<br>
   * <br>
   * 
   */
  public StrategyRewriteGraph(Term initial, StrategyExpression strat) {
    this(maudeJNI.new_StrategyRewriteGraph__SWIG_2(Term.getCPtr(initial), initial, StrategyExpression.getCPtr(strat), strat), true);
  }

  /**
   * Get the term of the given state.<br>
   * <br>
   * @param stateNr A state number.
   */
  public Term getStateTerm(int stateNr) {
    long cPtr = maudeJNI.StrategyRewriteGraph_getStateTerm(swigCPtr, this, stateNr);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the strategy that will be executed next<br>
   * from the given state.<br>
   * <br>
   * @param stateNr A state number.<br>
   * <br>
   * @return That strategy expression or null if there is<br>
   * no pending strategy in the current call or subsearch frame.
   */
  public StrategyExpression getStateStrategy(int stateNr) {
    long cPtr = maudeJNI.StrategyRewriteGraph_getStateStrategy(swigCPtr, this, stateNr);
    return (cPtr == 0) ? null : new StrategyExpression(cPtr, false);
  }

  /**
   * Get the transition that connects two states (if any).<br>
   * <br>
   * @param origin Origin state number.<br>
   * @param dest Destination state number.<br>
   * <br>
   * @return That transition if exists or a null pointer.
   */
  public StrategyGraphTransition getTransition(int origin, int dest) {
    long cPtr = maudeJNI.StrategyRewriteGraph_getTransition(swigCPtr, this, origin, dest);
    return (cPtr == 0) ? null : new StrategyGraphTransition(cPtr, false);
  }

  /**
   * Get the number of rewrites used to generate this graph,<br>
   * including the evaluation of atomic propositions.
   */
  public int getNrRewrites() {
    return maudeJNI.StrategyRewriteGraph_getNrRewrites(swigCPtr, this);
  }

  /**
   * Model check a given LTL formula.<br>
   * <br>
   * @param formula Term of the <code>Formula</code> sort.<br>
   * <br>
   * @return The result of model checking.
   */
  public ModelCheckResult modelCheck(Term formula) {
    long cPtr = maudeJNI.StrategyRewriteGraph_modelCheck(swigCPtr, this, Term.getCPtr(formula), formula);
    return (cPtr == 0) ? null : new ModelCheckResult(cPtr, true);
  }

  /**
   * Get the number of states in the graph.
   */
  public int getNrStates() {
    return maudeJNI.StrategyRewriteGraph_getNrStates(swigCPtr, this);
  }

  /**
   * Get the number of real (not merged) states in the graph (in linear time).
   */
  public int getNrRealStates() {
    return maudeJNI.StrategyRewriteGraph_getNrRealStates(swigCPtr, this);
  }

  /**
   * List the successors of a state in the graph.<br>
   * <br>
   * @param stateNr A state number.<br>
   * @param index A child index (from zero).<br>
   * <br>
   * @return The state number of a successor or -1.
   */
  public int getNextState(int stateNr, int index) {
    return maudeJNI.StrategyRewriteGraph_getNextState(swigCPtr, this, stateNr, index);
  }

  /**
   * Whether the state is a solution for the strategy.<br>
   * <br>
   * @param stateNr A state number.
   */
  public boolean isSolutionState(int stateNr) {
    return maudeJNI.StrategyRewriteGraph_isSolutionState(swigCPtr, this, stateNr);
  }

  /**
   * Cause of the transition in the graph.
   */
  public final static class TransitionType {
    /**
     *  rule application
     */
    public final static StrategyRewriteGraph.TransitionType RULE_APPLICATION = new StrategyRewriteGraph.TransitionType("RULE_APPLICATION");
    /**
     *  opaque strategy
     */
    public final static StrategyRewriteGraph.TransitionType OPAQUE_STRATEGY = new StrategyRewriteGraph.TransitionType("OPAQUE_STRATEGY");
    /**
     *  self-loops for solutions
     */
    public final static StrategyRewriteGraph.TransitionType SOLUTION = new StrategyRewriteGraph.TransitionType("SOLUTION");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static TransitionType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + TransitionType.class + " with value " + swigValue);
    }

    private TransitionType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private TransitionType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private TransitionType(String swigName, TransitionType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static TransitionType[] swigValues = { RULE_APPLICATION, OPAQUE_STRATEGY, SOLUTION };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
