/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Internal Maude vector.
 */
public class StratVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StratVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StratVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StratVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_StratVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct a vector.<br>
   * <br>
   * @param length The initial length.
   */
  public StratVector(long length) {
    this(maudeJNI.new_StratVector__SWIG_0(length), true);
  }

  /**
   * Construct a vector.<br>
   * <br>
   * 
   */
  public StratVector() {
    this(maudeJNI.new_StratVector__SWIG_1(), true);
  }

  /**
   * Is the vector empty?
   */
  public boolean empty() {
    return maudeJNI.StratVector_empty(swigCPtr, this);
  }

  /**
   * Size of the vector.
   */
  public long size() {
    return maudeJNI.StratVector_size(swigCPtr, this);
  }

  /**
   * Reserved capacity of the vector.
   */
  public long capacity() {
    return maudeJNI.StratVector_capacity(swigCPtr, this);
  }

  /**
   * Swap this vector's contents with another.<br>
   * <br>
   * @param other The other vector.
   */
  public void swap(StratVector other) {
    maudeJNI.StratVector_swap(swigCPtr, this, StratVector.getCPtr(other), other);
  }

  /**
   * Get a vector position value.<br>
   * <br>
   * @param n Vector position from zero.
   */
  public RewriteStrategy get(long n) {
    long cPtr = maudeJNI.StratVector_get(swigCPtr, this, n);
    return (cPtr == 0) ? null : new RewriteStrategy(cPtr, true);
  }

  /**
   * Set a vector position value.<br>
   * <br>
   * @param n Vector position from zero.<br>
   * @param value Value to be set.
   */
  public void set(long n, RewriteStrategy value) {
    maudeJNI.StratVector_set(swigCPtr, this, n, RewriteStrategy.getCPtr(value), value);
  }

  /**
   * Append a new element to the vector.
   */
  public void append(RewriteStrategy value) {
    maudeJNI.StratVector_append(swigCPtr, this, RewriteStrategy.getCPtr(value), value);
  }

  /**
   * Set the vector length to zero.
   */
  public void clear() {
    maudeJNI.StratVector_clear(swigCPtr, this);
  }

  /**
   * Resize the vector.<br>
   * <br>
   * @param new_size New size.
   */
  public void resize(long new_size) {
    maudeJNI.StratVector_resize(swigCPtr, this, new_size);
  }

}
