/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class StringVectorVector extends java.util.AbstractList<StringVector> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringVectorVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringVectorVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StringVectorVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_StringVectorVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringVectorVector(StringVector[] initialElements) {
    this();
    reserve(initialElements.length);

    for (StringVector element : initialElements) {
      add(element);
    }
  }

  public StringVectorVector(Iterable<StringVector> initialElements) {
    this();
    for (StringVector element : initialElements) {
      add(element);
    }
  }

  public StringVector get(int index) {
    return doGet(index);
  }

  public StringVector set(int index, StringVector e) {
    return doSet(index, e);
  }

  public boolean add(StringVector e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, StringVector e) {
    modCount++;
    doAdd(index, e);
  }

  public StringVector remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public StringVectorVector() {
    this(maudeJNI.new_StringVectorVector__SWIG_0(), true);
  }

  public StringVectorVector(StringVectorVector other) {
    this(maudeJNI.new_StringVectorVector__SWIG_1(StringVectorVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return maudeJNI.StringVectorVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    maudeJNI.StringVectorVector_clear(swigCPtr, this);
  }

  public StringVectorVector(int count, StringVector value) {
    this(maudeJNI.new_StringVectorVector__SWIG_2(count, StringVector.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return maudeJNI.StringVectorVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    maudeJNI.StringVectorVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return maudeJNI.StringVectorVector_doSize(swigCPtr, this);
  }

  private void doAdd(StringVector x) {
    maudeJNI.StringVectorVector_doAdd__SWIG_0(swigCPtr, this, StringVector.getCPtr(x), x);
  }

  private void doAdd(int index, StringVector x) {
    maudeJNI.StringVectorVector_doAdd__SWIG_1(swigCPtr, this, index, StringVector.getCPtr(x), x);
  }

  private StringVector doRemove(int index) {
    return new StringVector(maudeJNI.StringVectorVector_doRemove(swigCPtr, this, index), true);
  }

  private StringVector doGet(int index) {
    return new StringVector(maudeJNI.StringVectorVector_doGet(swigCPtr, this, index), false);
  }

  private StringVector doSet(int index, StringVector val) {
    return new StringVector(maudeJNI.StringVectorVector_doSet(swigCPtr, this, index, StringVector.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    maudeJNI.StringVectorVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
