/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Substitution (mapping from variables to terms).
 */
public class Substitution {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Substitution(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Substitution obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Substitution obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Substitution(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Create a substitution with the given variables and values.<br>
   * <br>
   * @param vars Variables in the substitution.<br>
   * @param values values Values for these variables in the substitution.
   */
  public Substitution(TermVector vars, TermVector values) {
    this(maudeJNI.new_Substitution(TermVector.getCPtr(vars), vars, TermVector.getCPtr(values), values), true);
  }

  /**
   * Get the number of variables in the substitution.
   */
  public int size() {
    return maudeJNI.Substitution_size(swigCPtr, this);
  }

  /**
   * Get the value of a given variable.<br>
   * <br>
   * @param variable The variable whose value is looked up.
   */
  public Term value(Term variable) {
    long cPtr = maudeJNI.Substitution_value(swigCPtr, this, Term.getCPtr(variable), variable);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the matched portion when matching with extension.<br>
   * <br>
   * @return The matched portion or null if the<br>
   * whole term matched.
   */
  public Term matchedPortion() {
    long cPtr = maudeJNI.Substitution_matchedPortion(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Find the value of a given variable by name.<br>
   * <br>
   * @param name Variable name (without sort).<br>
   * @param sort Sort of the variable (optional).<br>
   * <br>
   * @return The value of the variable or null if not found.<br>
   * If the sort of the variable is not given, multiple results<br>
   * are possible.
   */
  public Term find(String name, Sort sort) {
    long cPtr = maudeJNI.Substitution_find__SWIG_0(swigCPtr, this, name, Sort.getCPtr(sort), sort);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Find the value of a given variable by name.<br>
   * <br>
   * @param name Variable name (without sort).<br>
   * <br>
   * <br>
   * @return The value of the variable or null if not found.<br>
   * If the sort of the variable is not given, multiple results<br>
   * are possible.
   */
  public Term find(String name) {
    long cPtr = maudeJNI.Substitution_find__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Instantiate a term with this substitution.<br>
   * <br>
   * @param term The term to be instantiated.<br>
   * <br>
   * @return The instantiated term.
   */
  public Term instantiate(Term term) {
    long cPtr = maudeJNI.Substitution_instantiate(swigCPtr, this, Term.getCPtr(term), term);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get an iterator to the substitution assignments.
   */
  public Iterator iterator() {
    long cPtr = maudeJNI.Substitution_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new Iterator(cPtr, true);
  }

  public String toString() {
    return maudeJNI.Substitution_toString(swigCPtr, this);
  }

}
