/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A Maude symbol (operator at the kind level).
 */
public class Symbol extends ModuleItem {
  private transient long swigCPtr;

  protected Symbol(long cPtr, boolean cMemoryOwn) {
    super(maudeJNI.Symbol_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Symbol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Symbol obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Symbol(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Get the number of arguments.
   */
  public int arity() {
    return maudeJNI.Symbol_arity(swigCPtr, this);
  }

  /**
   * Get the kind for the given argument.<br>
   * <br>
   * @param argNr The argument index.
   */
  public Kind domainKind(int argNr) {
    long cPtr = maudeJNI.Symbol_domainKind(swigCPtr, this, argNr);
    return (cPtr == 0) ? null : new Kind(cPtr, true);
  }

  /**
   * Get the range sort of the symbol.
   */
  public Sort getRangeSort() {
    long cPtr = maudeJNI.Symbol_getRangeSort(swigCPtr, this);
    return (cPtr == 0) ? null : new Sort(cPtr, true);
  }

  /**
   * Get the hash value of the symbol.
   */
  public long hash() {
    return maudeJNI.Symbol_hash(swigCPtr, this);
  }

  /**
   * Check whether two symbols are the same.
   */
  public boolean equal(Symbol other) {
    return maudeJNI.Symbol_equal(swigCPtr, this, Symbol.getCPtr(other), other);
  }

  /**
   * Get the declarations of the symbol.
   */
  public OpDeclVector getOpDeclarations() {
    return new OpDeclVector(maudeJNI.Symbol_getOpDeclarations(swigCPtr, this), true);
  }

  /**
   * Build a term with this symbol and the given terms as arguments.
   */
  public Term makeTerm(TermVector args) {
    long cPtr = maudeJNI.Symbol_makeTerm(swigCPtr, this, TermVector.getCPtr(args), args);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * Get the metadata attribute of the given declaration of this symbol.<br>
   * <br>
   * @param index Index of the operator declaration.
   */
  public String getMetadata(int index) {
    return maudeJNI.Symbol_getMetadata(swigCPtr, this, index);
  }

  /**
   * Whether the symbol is associative.<br>
   * <br>
   * @deprecated use <code>hasAttr(OP_ASSOC)</code> instead.
   */
  public boolean isAssoc() {
    return maudeJNI.Symbol_isAssoc(swigCPtr, this);
  }

  /**
   * Whether the symbol has the given attribute.<br>
   * <br>
   * @param attr One of the <code>OP_*</code> constants for operator attributes.
   */
  public boolean hasAttr(int attr) {
    return maudeJNI.Symbol_hasAttr(swigCPtr, this, attr);
  }

  /**
   * Get the identity element for this symbol (if any).
   */
  public Term getIdentity() {
    long cPtr = maudeJNI.Symbol_getIdentity(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  /**
   * Get the reduction strategy of the symbol.
   */
  public IntVector getStrategy() {
    return new IntVector(maudeJNI.Symbol_getStrategy(swigCPtr, this), true);
  }

  /**
   * Get the frozen attribute of the symbol.<br>
   * <br>
   * @return The sequence of indices in the frozen attribute,<br>
   * where arguments are numbered from 0 instead of 1.
   */
  public IntVector getFrozen() {
    return new IntVector(maudeJNI.Symbol_getFrozen(swigCPtr, this), true);
  }

  /**
   * Get the format attribute of the symbol.<br>
   * <br>
   * @return The sequence of instruction words of the format<br>
   * specification, each of them a string.
   */
  public StringVector getFormat() {
    return new StringVector(maudeJNI.Symbol_getFormat(swigCPtr, this), true);
  }

  /**
   * Get the syntactic precedence of the symbol.
   */
  public int getPrec() {
    return maudeJNI.Symbol_getPrec(swigCPtr, this);
  }

  /**
   * Get the id-hooks of the special operator (or an empty sequence otherwise).<br>
   * <br>
   * @return A sequence of string sequences representing each an id-hook of<br>
   * the operator with its name followed by its arguments.
   */
  public StringVectorVector getIdHooks() {
    return new StringVectorVector(maudeJNI.Symbol_getIdHooks(swigCPtr, this), true);
  }

  public String toString() {
    return maudeJNI.Symbol_toString(swigCPtr, this);
  }

  /**
   * Get the line number information for this item as formatted by Maude.<br>
   * <br>
   * The format of the string is usually <code>filename, line line (module)</code><br>
   * where the second <code>line</code> is the integral line number, and <code>module</code> is<br>
   * the module type and name where this item was originally defined. The<br>
   * <code>filename</code> may be an actual quoted filename or some special name<br>
   * between angle brackets.
   */
  public String getLineNumber() {
    return maudeJNI.Symbol_getLineNumber(swigCPtr, this);
  }

}
