/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public final class SymbolAttribute {
  /**
   *  associative
   */
  public final static SymbolAttribute OP_ASSOC = new SymbolAttribute("OP_ASSOC");
  /**
   *  commutative
   */
  public final static SymbolAttribute OP_COMM = new SymbolAttribute("OP_COMM");
  /**
   *  iterable
   */
  public final static SymbolAttribute OP_ITER = new SymbolAttribute("OP_ITER");
  /**
   *  idempotent
   */
  public final static SymbolAttribute OP_IDEM = new SymbolAttribute("OP_IDEM");
  /**
   *  with left identity element
   */
  public final static SymbolAttribute OP_LEFT_ID = new SymbolAttribute("OP_LEFT_ID");
  /**
   *  with right identity element
   */
  public final static SymbolAttribute OP_RIGHT_ID = new SymbolAttribute("OP_RIGHT_ID");
  /**
   *  with memoization
   */
  public final static SymbolAttribute OP_MEMO = new SymbolAttribute("OP_MEMO");
  /**
   *  special
   */
  public final static SymbolAttribute OP_SPECIAL = new SymbolAttribute("OP_SPECIAL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SymbolAttribute swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SymbolAttribute.class + " with value " + swigValue);
  }

  private SymbolAttribute(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SymbolAttribute(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SymbolAttribute(String swigName, SymbolAttribute swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SymbolAttribute[] swigValues = { OP_ASSOC, OP_COMM, OP_ITER, OP_IDEM, OP_LEFT_ID, OP_RIGHT_ID, OP_MEMO, OP_SPECIAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

