/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class TermVector extends java.util.AbstractList<Term> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TermVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TermVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TermVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_TermVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TermVector(Term[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Term element : initialElements) {
      add(element);
    }
  }

  public TermVector(Iterable<Term> initialElements) {
    this();
    for (Term element : initialElements) {
      add(element);
    }
  }

  public Term get(int index) {
    return doGet(index);
  }

  public Term set(int index, Term e) {
    return doSet(index, e);
  }

  public boolean add(Term e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Term e) {
    modCount++;
    doAdd(index, e);
  }

  public Term remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TermVector() {
    this(maudeJNI.new_TermVector__SWIG_0(), true);
  }

  public TermVector(TermVector other) {
    this(maudeJNI.new_TermVector__SWIG_1(TermVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return maudeJNI.TermVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    maudeJNI.TermVector_clear(swigCPtr, this);
  }

  public TermVector(int count, Term value) {
    this(maudeJNI.new_TermVector__SWIG_2(count, Term.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return maudeJNI.TermVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    maudeJNI.TermVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return maudeJNI.TermVector_doSize(swigCPtr, this);
  }

  private void doAdd(Term x) {
    maudeJNI.TermVector_doAdd__SWIG_0(swigCPtr, this, Term.getCPtr(x), x);
  }

  private void doAdd(int index, Term x) {
    maudeJNI.TermVector_doAdd__SWIG_1(swigCPtr, this, index, Term.getCPtr(x), x);
  }

  private Term doRemove(int index) {
    long cPtr = maudeJNI.TermVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  private Term doGet(int index) {
    long cPtr = maudeJNI.TermVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  private Term doSet(int index, Term val) {
    long cPtr = maudeJNI.TermVector_doSet(swigCPtr, this, index, Term.getCPtr(val), val);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    maudeJNI.TermVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
