/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class TermPairVector extends java.util.AbstractList<TermPair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TermPairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TermPairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TermPairVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_TermPairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TermPairVector(TermPair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TermPair element : initialElements) {
      add(element);
    }
  }

  public TermPairVector(Iterable<TermPair> initialElements) {
    this();
    for (TermPair element : initialElements) {
      add(element);
    }
  }

  public TermPair get(int index) {
    return doGet(index);
  }

  public TermPair set(int index, TermPair e) {
    return doSet(index, e);
  }

  public boolean add(TermPair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TermPair e) {
    modCount++;
    doAdd(index, e);
  }

  public TermPair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TermPairVector() {
    this(maudeJNI.new_TermPairVector__SWIG_0(), true);
  }

  public TermPairVector(TermPairVector other) {
    this(maudeJNI.new_TermPairVector__SWIG_1(TermPairVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return maudeJNI.TermPairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    maudeJNI.TermPairVector_clear(swigCPtr, this);
  }

  public TermPairVector(int count, TermPair value) {
    this(maudeJNI.new_TermPairVector__SWIG_2(count, TermPair.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return maudeJNI.TermPairVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    maudeJNI.TermPairVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return maudeJNI.TermPairVector_doSize(swigCPtr, this);
  }

  private void doAdd(TermPair x) {
    maudeJNI.TermPairVector_doAdd__SWIG_0(swigCPtr, this, TermPair.getCPtr(x), x);
  }

  private void doAdd(int index, TermPair x) {
    maudeJNI.TermPairVector_doAdd__SWIG_1(swigCPtr, this, index, TermPair.getCPtr(x), x);
  }

  private TermPair doRemove(int index) {
    return new TermPair(maudeJNI.TermPairVector_doRemove(swigCPtr, this, index), true);
  }

  private TermPair doGet(int index) {
    return new TermPair(maudeJNI.TermPairVector_doGet(swigCPtr, this, index), false);
  }

  private TermPair doSet(int index, TermPair val) {
    return new TermPair(maudeJNI.TermPairVector_doSet(swigCPtr, this, index, TermPair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    maudeJNI.TermPairVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
