/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class TermSubstitutionPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TermSubstitutionPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TermSubstitutionPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TermSubstitutionPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_TermSubstitutionPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TermSubstitutionPair() {
    this(maudeJNI.new_TermSubstitutionPair__SWIG_0(), true);
  }

  public TermSubstitutionPair(Term first, Substitution second) {
    this(maudeJNI.new_TermSubstitutionPair__SWIG_1(Term.getCPtr(first), first, Substitution.getCPtr(second), second), true);
  }

  public TermSubstitutionPair(TermSubstitutionPair other) {
    this(maudeJNI.new_TermSubstitutionPair__SWIG_2(TermSubstitutionPair.getCPtr(other), other), true);
  }

  public void setFirst(Term value) {
    maudeJNI.TermSubstitutionPair_first_set(swigCPtr, this, Term.getCPtr(value), value);
  }

  public Term getFirst() {
    long cPtr = maudeJNI.TermSubstitutionPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  public void setSecond(Substitution value) {
    maudeJNI.TermSubstitutionPair_second_set(swigCPtr, this, Substitution.getCPtr(value), value);
  }

  public Substitution getSecond() {
    long cPtr = maudeJNI.TermSubstitutionPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Substitution(cPtr, false);
  }

}
