/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * Maude term with its associated operations.
 */
public class Term {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Term(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Term obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Term obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_Term(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Get the top symbol of this term.
   */
  public Symbol symbol() {
    long cPtr = maudeJNI.Term_symbol(swigCPtr, this);
    return (cPtr == 0) ? null : new Symbol(cPtr, true);
  }

  /**
   * Is this term ground?
   */
  public boolean ground() {
    return maudeJNI.Term_ground(swigCPtr, this);
  }

  /**
   * Compare two terms for equality.<br>
   * <br>
   * @param other The second term to be compared.
   */
  public boolean equal(Term other) {
    return maudeJNI.Term_equal(swigCPtr, this, Term.getCPtr(other), other);
  }

  /**
   * Check whether the sort of this term is a subtype of the given sort.<br>
   * <br>
   * @param sort The pretended supertype.
   */
  public boolean leq(Sort sort) {
    return maudeJNI.Term_leq(swigCPtr, this, Sort.getCPtr(sort), sort);
  }

  /**
   * Get the sort of this term.
   */
  public Sort getSort() {
    long cPtr = maudeJNI.Term_getSort(swigCPtr, this);
    return (cPtr == 0) ? null : new Sort(cPtr, true);
  }

  /**
   * Normalize this term modulo axioms.<br>
   * <br>
   * @param full Whether to normalize in depth.
   */
  public void normalize(boolean full) {
    maudeJNI.Term_normalize__SWIG_0(swigCPtr, this, full);
  }

  /**
   * Normalize this term modulo axioms.<br>
   * <br>
   * 
   */
  public void normalize() {
    maudeJNI.Term_normalize__SWIG_1(swigCPtr, this);
  }

  /**
   * Reduce this term.<br>
   * <br>
   * @return The total number of rewrites.
   */
  public int reduce() {
    return maudeJNI.Term_reduce(swigCPtr, this);
  }

  /**
   * Rewrite a term following the semantics of the <code>rewrite</code> command.<br>
   * <br>
   * @param bound An upper bound on the number of rule rewrites.<br>
   * <br>
   * @return The total number of rewrites.
   */
  public int rewrite(int bound) {
    return maudeJNI.Term_rewrite__SWIG_0(swigCPtr, this, bound);
  }

  /**
   * Rewrite a term following the semantics of the <code>rewrite</code> command.<br>
   * <br>
   * <br>
   * <br>
   * @return The total number of rewrites.
   */
  public int rewrite() {
    return maudeJNI.Term_rewrite__SWIG_1(swigCPtr, this);
  }

  /**
   * Rewrite a term following the semantics of the <code>frewrite</code> command.<br>
   * <br>
   * @param bound An upper bound on the number of rule rewrites.<br>
   * @param gas An upper bound on the number of rule rewrites per position.<br>
   * <br>
   * @return The total number of rewrites.
   */
  public int frewrite(int bound, int gas) {
    return maudeJNI.Term_frewrite__SWIG_0(swigCPtr, this, bound, gas);
  }

  /**
   * Rewrite a term following the semantics of the <code>frewrite</code> command.<br>
   * <br>
   * @param bound An upper bound on the number of rule rewrites.<br>
   * <br>
   * <br>
   * @return The total number of rewrites.
   */
  public int frewrite(int bound) {
    return maudeJNI.Term_frewrite__SWIG_1(swigCPtr, this, bound);
  }

  /**
   * Rewrite a term following the semantics of the <code>frewrite</code> command.<br>
   * <br>
   * <br>
   * <br>
   * <br>
   * @return The total number of rewrites.
   */
  public int frewrite() {
    return maudeJNI.Term_frewrite__SWIG_2(swigCPtr, this);
  }

  /**
   * Rewrite a term following the semantics of the <code>erewrite</code> command.<br>
   * <br>
   * @param bound An upper bound on the number of rule rewrites.<br>
   * @param gas An upper bound on the number of rule rewrites by position.<br>
   * <br>
   * @return The result and the total number of rewrites (the original<br>
   * term is not modified).
   */
  public TermIntPair erewrite(int bound, int gas) {
    return new TermIntPair(maudeJNI.Term_erewrite__SWIG_0(swigCPtr, this, bound, gas), true);
  }

  /**
   * Rewrite a term following the semantics of the <code>erewrite</code> command.<br>
   * <br>
   * @param bound An upper bound on the number of rule rewrites.<br>
   * <br>
   * <br>
   * @return The result and the total number of rewrites (the original<br>
   * term is not modified).
   */
  public TermIntPair erewrite(int bound) {
    return new TermIntPair(maudeJNI.Term_erewrite__SWIG_1(swigCPtr, this, bound), true);
  }

  /**
   * Rewrite a term following the semantics of the <code>erewrite</code> command.<br>
   * <br>
   * <br>
   * <br>
   * <br>
   * @return The result and the total number of rewrites (the original<br>
   * term is not modified).
   */
  public TermIntPair erewrite() {
    return new TermIntPair(maudeJNI.Term_erewrite__SWIG_2(swigCPtr, this), true);
  }

  /**
   * Match this term into a given pattern.<br>
   * <br>
   * @param pattern Pattern term.<br>
   * @param condition Equational condition that solutions must satisfy.<br>
   * @param withExtension Whether the matching should be done with extension modulo axioms<br>
   * (deprecated, use <code>maxDepth=0</code> instead).<br>
   * @param minDepth Minimum matching depth.<br>
   * @param maxDepth Maximum matching depth (<code>-1</code> to match on top without extension, <code>0</code><br>
   * to match on top with extension, <code>UNBOUNDED</code> to match anywhere, or any intermediate value).<br>
   * <br>
   * @return An object to iterate through matches.
   */
  public MatchSearchState match(Term pattern, Condition condition, boolean withExtension, int minDepth, int maxDepth) {
    long cPtr = maudeJNI.Term_match__SWIG_0(swigCPtr, this, Term.getCPtr(pattern), pattern, Condition.getCPtr(condition), condition, withExtension, minDepth, maxDepth);
    return (cPtr == 0) ? null : new MatchSearchState(cPtr, true);
  }

  /**
   * Match this term into a given pattern.<br>
   * <br>
   * @param pattern Pattern term.<br>
   * @param condition Equational condition that solutions must satisfy.<br>
   * @param withExtension Whether the matching should be done with extension modulo axioms<br>
   * (deprecated, use <code>maxDepth=0</code> instead).<br>
   * @param minDepth Minimum matching depth.<br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public MatchSearchState match(Term pattern, Condition condition, boolean withExtension, int minDepth) {
    long cPtr = maudeJNI.Term_match__SWIG_1(swigCPtr, this, Term.getCPtr(pattern), pattern, Condition.getCPtr(condition), condition, withExtension, minDepth);
    return (cPtr == 0) ? null : new MatchSearchState(cPtr, true);
  }

  /**
   * Match this term into a given pattern.<br>
   * <br>
   * @param pattern Pattern term.<br>
   * @param condition Equational condition that solutions must satisfy.<br>
   * @param withExtension Whether the matching should be done with extension modulo axioms<br>
   * (deprecated, use <code>maxDepth=0</code> instead).<br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public MatchSearchState match(Term pattern, Condition condition, boolean withExtension) {
    long cPtr = maudeJNI.Term_match__SWIG_2(swigCPtr, this, Term.getCPtr(pattern), pattern, Condition.getCPtr(condition), condition, withExtension);
    return (cPtr == 0) ? null : new MatchSearchState(cPtr, true);
  }

  /**
   * Match this term into a given pattern.<br>
   * <br>
   * @param pattern Pattern term.<br>
   * @param condition Equational condition that solutions must satisfy.<br>
   * <br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public MatchSearchState match(Term pattern, Condition condition) {
    long cPtr = maudeJNI.Term_match__SWIG_3(swigCPtr, this, Term.getCPtr(pattern), pattern, Condition.getCPtr(condition), condition);
    return (cPtr == 0) ? null : new MatchSearchState(cPtr, true);
  }

  /**
   * Match this term into a given pattern.<br>
   * <br>
   * @param pattern Pattern term.<br>
   * <br>
   * <br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public MatchSearchState match(Term pattern) {
    long cPtr = maudeJNI.Term_match__SWIG_4(swigCPtr, this, Term.getCPtr(pattern), pattern);
    return (cPtr == 0) ? null : new MatchSearchState(cPtr, true);
  }

  /**
   * Rewrite a term following a strategy.<br>
   * <br>
   * @param expr A strategy expression.<br>
   * @param depth Whether to perform a depth-first search. By default, a fair search is used.<br>
   * <br>
   * @return An object to iterate through strategy solutions.
   */
  public StrategicSearch srewrite(StrategyExpression expr, boolean depth) {
    long cPtr = maudeJNI.Term_srewrite__SWIG_0(swigCPtr, this, StrategyExpression.getCPtr(expr), expr, depth);
    return (cPtr == 0) ? null : new StrategicSearch(cPtr, true);
  }

  /**
   * Rewrite a term following a strategy.<br>
   * <br>
   * @param expr A strategy expression.<br>
   * <br>
   * <br>
   * @return An object to iterate through strategy solutions.
   */
  public StrategicSearch srewrite(StrategyExpression expr) {
    long cPtr = maudeJNI.Term_srewrite__SWIG_1(swigCPtr, this, StrategyExpression.getCPtr(expr), expr);
    return (cPtr == 0) ? null : new StrategicSearch(cPtr, true);
  }

  /**
   * Search states that match into a given pattern and satisfy a given<br>
   * condition by rewriting from this term.<br>
   * <br>
   * @param type Type of search (number of steps).<br>
   * @param target Patterm term.<br>
   * @param condition Condition that solutions must satisfy.<br>
   * @param depth Depth bound.<br>
   * <br>
   * @return An object to iterate through matches.
   */
  public RewriteSequenceSearch search(SearchType type, Term target, Condition condition, int depth) {
    long cPtr = maudeJNI.Term_search__SWIG_0(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target, Condition.getCPtr(condition), condition, depth);
    return (cPtr == 0) ? null : new RewriteSequenceSearch(cPtr, true);
  }

  /**
   * Search states that match into a given pattern and satisfy a given<br>
   * condition by rewriting from this term.<br>
   * <br>
   * @param type Type of search (number of steps).<br>
   * @param target Patterm term.<br>
   * @param condition Condition that solutions must satisfy.<br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public RewriteSequenceSearch search(SearchType type, Term target, Condition condition) {
    long cPtr = maudeJNI.Term_search__SWIG_1(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target, Condition.getCPtr(condition), condition);
    return (cPtr == 0) ? null : new RewriteSequenceSearch(cPtr, true);
  }

  /**
   * Search states that match into a given pattern and satisfy a given<br>
   * condition by rewriting from this term.<br>
   * <br>
   * @param type Type of search (number of steps).<br>
   * @param target Patterm term.<br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public RewriteSequenceSearch search(SearchType type, Term target) {
    long cPtr = maudeJNI.Term_search__SWIG_2(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target);
    return (cPtr == 0) ? null : new RewriteSequenceSearch(cPtr, true);
  }

  /**
   * Search states that match into a given pattern and satisfy a given<br>
   * condition by rewriting from this term using a strategy.<br>
   * <br>
   * @param type Type of search (number of steps).<br>
   * @param target Patterm term.<br>
   * @param strategy Strategy to control the search.<br>
   * @param condition Condition that solutions must satisfy.<br>
   * @param depth Depth bound.<br>
   * <br>
   * @return An object to iterate through matches.
   */
  public StrategySequenceSearch search(SearchType type, Term target, StrategyExpression strategy, Condition condition, int depth) {
    long cPtr = maudeJNI.Term_search__SWIG_3(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target, StrategyExpression.getCPtr(strategy), strategy, Condition.getCPtr(condition), condition, depth);
    return (cPtr == 0) ? null : new StrategySequenceSearch(cPtr, true);
  }

  /**
   * Search states that match into a given pattern and satisfy a given<br>
   * condition by rewriting from this term using a strategy.<br>
   * <br>
   * @param type Type of search (number of steps).<br>
   * @param target Patterm term.<br>
   * @param strategy Strategy to control the search.<br>
   * @param condition Condition that solutions must satisfy.<br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public StrategySequenceSearch search(SearchType type, Term target, StrategyExpression strategy, Condition condition) {
    long cPtr = maudeJNI.Term_search__SWIG_4(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target, StrategyExpression.getCPtr(strategy), strategy, Condition.getCPtr(condition), condition);
    return (cPtr == 0) ? null : new StrategySequenceSearch(cPtr, true);
  }

  /**
   * Search states that match into a given pattern and satisfy a given<br>
   * condition by rewriting from this term using a strategy.<br>
   * <br>
   * @param type Type of search (number of steps).<br>
   * @param target Patterm term.<br>
   * @param strategy Strategy to control the search.<br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through matches.
   */
  public StrategySequenceSearch search(SearchType type, Term target, StrategyExpression strategy) {
    long cPtr = maudeJNI.Term_search__SWIG_5(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target, StrategyExpression.getCPtr(strategy), strategy);
    return (cPtr == 0) ? null : new StrategySequenceSearch(cPtr, true);
  }

  /**
   * Compute the most general variants of this term.<br>
   * <br>
   * @param irredundant Whether to obtain irredundant variants<br>
   * (for theories with the finite variant property).<br>
   * @param irreducible Irreducible terms constraint.<br>
   * <br>
   * @return An object to iterate through variants.
   */
  public VariantSearch get_variants(boolean irredundant, TermVector irreducible) {
    long cPtr = maudeJNI.Term_get_variants__SWIG_0(swigCPtr, this, irredundant, TermVector.getCPtr(irreducible), irreducible);
    return (cPtr == 0) ? null : new VariantSearch(cPtr, false);
  }

  /**
   * Compute the most general variants of this term.<br>
   * <br>
   * @param irredundant Whether to obtain irredundant variants<br>
   * (for theories with the finite variant property).<br>
   * <br>
   * <br>
   * @return An object to iterate through variants.
   */
  public VariantSearch get_variants(boolean irredundant) {
    long cPtr = maudeJNI.Term_get_variants__SWIG_1(swigCPtr, this, irredundant);
    return (cPtr == 0) ? null : new VariantSearch(cPtr, false);
  }

  /**
   * Compute the most general variants of this term.<br>
   * <br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through variants.
   */
  public VariantSearch get_variants() {
    long cPtr = maudeJNI.Term_get_variants__SWIG_2(swigCPtr, this);
    return (cPtr == 0) ? null : new VariantSearch(cPtr, false);
  }

  /**
   * Narrowing-based search of terms that unify with the given target.<br>
   * <br>
   * @param type Type of the search (number of steps).<br>
   * @param target The pattern that has to be reached.<br>
   * @param depth Depth bound (<code>-1</code> for unbounded).<br>
   * @param flags Narrowing search flags (<code>fold</code>, <code>vfold</code>, <code>path</code>, <code>delay</code>, or <code>filter</code> flag).<br>
   * <br>
   * @return An object to iterate through solutions.
   */
  public NarrowingSequenceSearch vu_narrow(SearchType type, Term target, int depth, NarrowingFlags flags) {
    long cPtr = maudeJNI.Term_vu_narrow__SWIG_0(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target, depth, flags.swigValue());
    return (cPtr == 0) ? null : new NarrowingSequenceSearch(cPtr, false);
  }

  /**
   * Narrowing-based search of terms that unify with the given target.<br>
   * <br>
   * @param type Type of the search (number of steps).<br>
   * @param target The pattern that has to be reached.<br>
   * @param depth Depth bound (<code>-1</code> for unbounded).<br>
   * <br>
   * <br>
   * @return An object to iterate through solutions.
   */
  public NarrowingSequenceSearch vu_narrow(SearchType type, Term target, int depth) {
    long cPtr = maudeJNI.Term_vu_narrow__SWIG_1(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target, depth);
    return (cPtr == 0) ? null : new NarrowingSequenceSearch(cPtr, false);
  }

  /**
   * Narrowing-based search of terms that unify with the given target.<br>
   * <br>
   * @param type Type of the search (number of steps).<br>
   * @param target The pattern that has to be reached.<br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through solutions.
   */
  public NarrowingSequenceSearch vu_narrow(SearchType type, Term target) {
    long cPtr = maudeJNI.Term_vu_narrow__SWIG_2(swigCPtr, this, type.swigValue(), Term.getCPtr(target), target);
    return (cPtr == 0) ? null : new NarrowingSequenceSearch(cPtr, false);
  }

  /**
   * Apply any rule with the given label.<br>
   * <br>
   * @param label Rule label (or null for any executable rule).<br>
   * @param substitution Initial substitution that will be applied on the rule before matching.<br>
   * @param minDepth Minimum matching depth.<br>
   * @param maxDepth Maximum matching depth.<br>
   * <br>
   * @return An object to iterate through the rewritten terms.
   */
  public RewriteSearchState apply(String label, Substitution substitution, int minDepth, int maxDepth) {
    long cPtr = maudeJNI.Term_apply__SWIG_0(swigCPtr, this, label, Substitution.getCPtr(substitution), substitution, minDepth, maxDepth);
    return (cPtr == 0) ? null : new RewriteSearchState(cPtr, true);
  }

  /**
   * Apply any rule with the given label.<br>
   * <br>
   * @param label Rule label (or null for any executable rule).<br>
   * @param substitution Initial substitution that will be applied on the rule before matching.<br>
   * @param minDepth Minimum matching depth.<br>
   * <br>
   * <br>
   * @return An object to iterate through the rewritten terms.
   */
  public RewriteSearchState apply(String label, Substitution substitution, int minDepth) {
    long cPtr = maudeJNI.Term_apply__SWIG_1(swigCPtr, this, label, Substitution.getCPtr(substitution), substitution, minDepth);
    return (cPtr == 0) ? null : new RewriteSearchState(cPtr, true);
  }

  /**
   * Apply any rule with the given label.<br>
   * <br>
   * @param label Rule label (or null for any executable rule).<br>
   * @param substitution Initial substitution that will be applied on the rule before matching.<br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through the rewritten terms.
   */
  public RewriteSearchState apply(String label, Substitution substitution) {
    long cPtr = maudeJNI.Term_apply__SWIG_2(swigCPtr, this, label, Substitution.getCPtr(substitution), substitution);
    return (cPtr == 0) ? null : new RewriteSearchState(cPtr, true);
  }

  /**
   * Apply any rule with the given label.<br>
   * <br>
   * @param label Rule label (or null for any executable rule).<br>
   * <br>
   * <br>
   * <br>
   * <br>
   * @return An object to iterate through the rewritten terms.
   */
  public RewriteSearchState apply(String label) {
    long cPtr = maudeJNI.Term_apply__SWIG_3(swigCPtr, this, label);
    return (cPtr == 0) ? null : new RewriteSearchState(cPtr, true);
  }

  /**
   * Check an SMT formula.<br>
   * <br>
   * @return A string, either <code>sat</code>, <code>unsat</code> or <code>undecided</code>.
   */
  public String check() {
    return maudeJNI.Term_check(swigCPtr, this);
  }

  /**
   * Iterate over the arguments of this term.<br>
   * <br>
   * @param normalize Whether to normalize before iterating over its arguments.
   */
  public ArgumentIterator arguments(boolean normalize) {
    long cPtr = maudeJNI.Term_arguments__SWIG_0(swigCPtr, this, normalize);
    return (cPtr == 0) ? null : new ArgumentIterator(cPtr, true);
  }

  /**
   * Iterate over the arguments of this term.<br>
   * <br>
   * 
   */
  public ArgumentIterator arguments() {
    long cPtr = maudeJNI.Term_arguments__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ArgumentIterator(cPtr, true);
  }

  /**
   * Get the floating-point number represented by the given term or<br>
   * zero otherwise.
   */
  public double toFloat() {
    return maudeJNI.Term_toFloat(swigCPtr, this);
  }

  /**
   * Get the integer number represented by the given term or<br>
   * zero otherwise.
   */
  public int toInt() {
    return maudeJNI.Term_toInt(swigCPtr, this);
  }

  /**
   * Get whether the term is a variable.
   */
  public boolean isVariable() {
    return maudeJNI.Term_isVariable(swigCPtr, this);
  }

  /**
   * Get the name of the variable if the current term is a variable or<br>
   * a null value otherwise.
   */
  public String getVarName() {
    return maudeJNI.Term_getVarName(swigCPtr, this);
  }

  /**
   * Get the exponent of an iterable symbol or zero otherwise.
   */
  public long getIterExponent() {
    return maudeJNI.Term_getIterExponent(swigCPtr, this);
  }

  /**
   * Get the hash value of the term.
   */
  public long hash() {
    return maudeJNI.Term_hash(swigCPtr, this);
  }

  /**
   * Get a copy of this term.
   */
  public Term copy() {
    long cPtr = maudeJNI.Term_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, true);
  }

  /**
   * An empty condition to be used as a placeholder.
   */
  public static Condition getNO_CONDITION() {
    long cPtr = maudeJNI.Term_NO_CONDITION_get();
    return (cPtr == 0) ? null : new Condition(cPtr, false);
  }

  /**
   * Pretty prints this term.<br>
   * <br>
   * @param flags Flags that affect the term output.
   */
  public String prettyPrint(PrintFlags flags) {
    return maudeJNI.Term_prettyPrint(swigCPtr, this, flags.swigValue());
  }

  /**
   * Obtain the LaTeX representation of this term.
   */
  public String toLatex() {
    return maudeJNI.Term_toLatex(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.Term_toString(swigCPtr, this);
  }

}
