/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class TermPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TermPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TermPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TermPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_TermPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TermPair() {
    this(maudeJNI.new_TermPair__SWIG_0(), true);
  }

  public TermPair(Term first, Term second) {
    this(maudeJNI.new_TermPair__SWIG_1(Term.getCPtr(first), first, Term.getCPtr(second), second), true);
  }

  public TermPair(TermPair other) {
    this(maudeJNI.new_TermPair__SWIG_2(TermPair.getCPtr(other), other), true);
  }

  public void setFirst(Term value) {
    maudeJNI.TermPair_first_set(swigCPtr, this, Term.getCPtr(value), value);
  }

  public Term getFirst() {
    long cPtr = maudeJNI.TermPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  public void setSecond(Term value) {
    maudeJNI.TermPair_second_set(swigCPtr, this, Term.getCPtr(value), value);
  }

  public Term getSecond() {
    long cPtr = maudeJNI.TermPair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

}
