/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class TermIntPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TermIntPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TermIntPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TermIntPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_TermIntPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TermIntPair() {
    this(maudeJNI.new_TermIntPair__SWIG_0(), true);
  }

  public TermIntPair(Term first, int second) {
    this(maudeJNI.new_TermIntPair__SWIG_1(Term.getCPtr(first), first, second), true);
  }

  public TermIntPair(TermIntPair other) {
    this(maudeJNI.new_TermIntPair__SWIG_2(TermIntPair.getCPtr(other), other), true);
  }

  public void setFirst(Term value) {
    maudeJNI.TermIntPair_first_set(swigCPtr, this, Term.getCPtr(value), value);
  }

  public Term getFirst() {
    long cPtr = maudeJNI.TermIntPair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Term(cPtr, false);
  }

  public void setSecond(int value) {
    maudeJNI.TermIntPair_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return maudeJNI.TermIntPair_second_get(swigCPtr, this);
  }

}
