/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class TokenVector extends java.util.AbstractList<Token> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TokenVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TokenVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TokenVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_TokenVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TokenVector(Token[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Token element : initialElements) {
      add(element);
    }
  }

  public TokenVector(Iterable<Token> initialElements) {
    this();
    for (Token element : initialElements) {
      add(element);
    }
  }

  public Token get(int index) {
    return doGet(index);
  }

  public Token set(int index, Token e) {
    return doSet(index, e);
  }

  public boolean add(Token e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Token e) {
    modCount++;
    doAdd(index, e);
  }

  public Token remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TokenVector() {
    this(maudeJNI.new_TokenVector__SWIG_0(), true);
  }

  public TokenVector(TokenVector other) {
    this(maudeJNI.new_TokenVector__SWIG_1(TokenVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return maudeJNI.TokenVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    maudeJNI.TokenVector_clear(swigCPtr, this);
  }

  public TokenVector(int count, Token value) {
    this(maudeJNI.new_TokenVector__SWIG_2(count, Token.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return maudeJNI.TokenVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    maudeJNI.TokenVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return maudeJNI.TokenVector_doSize(swigCPtr, this);
  }

  private void doAdd(Token x) {
    maudeJNI.TokenVector_doAdd__SWIG_0(swigCPtr, this, Token.getCPtr(x), x);
  }

  private void doAdd(int index, Token x) {
    maudeJNI.TokenVector_doAdd__SWIG_1(swigCPtr, this, index, Token.getCPtr(x), x);
  }

  private Token doRemove(int index) {
    return new Token(maudeJNI.TokenVector_doRemove(swigCPtr, this, index), true);
  }

  private Token doGet(int index) {
    return new Token(maudeJNI.TokenVector_doGet(swigCPtr, this, index), false);
  }

  private Token doSet(int index, Token val) {
    return new Token(maudeJNI.TokenVector_doSet(swigCPtr, this, index, Token.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    maudeJNI.TokenVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
