/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

		import java.util.Iterator;
		import java.util.NoSuchElementException;
	
/**
 * An iterator through unifiers.
 */
public class UnificationProblem implements Iterable<Substitution>, Iterator<Substitution> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnificationProblem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnificationProblem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UnificationProblem obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_UnificationProblem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

		private transient Substitution last = null;
		private transient boolean advanced = false;

		public Iterator<Substitution> iterator() {
			return this;
		}

		public boolean hasNext() {
			if (!advanced) {
				last = __next();
				advanced = true;
			}
			return last != null;
		}

		public Substitution next() {
			if (!advanced)
				hasNext();
			if (last == null)
				throw new NoSuchElementException("no more solutions");
			advanced = false;
			return last;
		}
	
  /**
   * Get the next unifier.<br>
   * <br>
   * @return That unifier or null pointer if there is no more.
   */
  public Substitution __next() {
    long cPtr = maudeJNI.UnificationProblem___next(swigCPtr, this);
    return (cPtr == 0) ? null : new Substitution(cPtr, true);
  }

}
