/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

		import java.util.Iterator;
		import java.util.NoSuchElementException;
	
/**
 * An iterator through variants.
 */
public class VariantSearch implements Iterable<TermSubstitutionPair>, Iterator<TermSubstitutionPair> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VariantSearch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VariantSearch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VariantSearch obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_VariantSearch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

		private transient TermSubstitutionPair last = null;
		private transient boolean advanced = false;

		public Iterator<TermSubstitutionPair> iterator() {
			return this;
		}

		public boolean hasNext() {
			if (!advanced) {
				last = __next();
				advanced = true;
			}
			return last != null;
		}

		public TermSubstitutionPair next() {
			if (!advanced)
				hasNext();
			if (last == null)
				throw new NoSuchElementException("no more solutions");
			advanced = false;
			return last;
		}
	
  /**
   * Whether some variants may have been missed due to incomplete unification algorithms.
   */
  public boolean isIncomplete() {
    return maudeJNI.VariantSearch_isIncomplete(swigCPtr, this);
  }

  /**
   * Get the next variant.<br>
   * <br>
   * @return The variant term or null if there is no more.
   */
  public TermSubstitutionPair __next() {
    long cPtr = maudeJNI.VariantSearch___next(swigCPtr, this);
    return (cPtr == 0) ? null : new TermSubstitutionPair(cPtr, true);
  }

}
