/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

/**
 * A Maude view.
 */
public class View {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected View(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(View obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(View obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_View(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Get the <i>from</i> theory of the view.
   */
  public Module getFromTheory() {
    long cPtr = maudeJNI.View_getFromTheory(swigCPtr, this);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  /**
   * Get the <i>to</i> module of the view.
   */
  public Module getToModule() {
    long cPtr = maudeJNI.View_getToModule(swigCPtr, this);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  /**
   * Get the LaTeX representation of the view.<br>
   * <br>
   * @param all Whether to show the processed view.
   */
  public String toLatex(boolean all) {
    return maudeJNI.View_toLatex__SWIG_0(swigCPtr, this, all);
  }

  /**
   * Get the LaTeX representation of the view.<br>
   * <br>
   * 
   */
  public String toLatex() {
    return maudeJNI.View_toLatex__SWIG_1(swigCPtr, this);
  }

  public String toString() {
    return maudeJNI.View_toString(swigCPtr, this);
  }

}
