/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package es.ucm.maude.bindings;

public class ViewVector extends java.util.AbstractList<View> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ViewVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ViewVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ViewVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maudeJNI.delete_ViewVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ViewVector(View[] initialElements) {
    this();
    reserve(initialElements.length);

    for (View element : initialElements) {
      add(element);
    }
  }

  public ViewVector(Iterable<View> initialElements) {
    this();
    for (View element : initialElements) {
      add(element);
    }
  }

  public View get(int index) {
    return doGet(index);
  }

  public View set(int index, View e) {
    return doSet(index, e);
  }

  public boolean add(View e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, View e) {
    modCount++;
    doAdd(index, e);
  }

  public View remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public ViewVector() {
    this(maudeJNI.new_ViewVector__SWIG_0(), true);
  }

  public ViewVector(ViewVector other) {
    this(maudeJNI.new_ViewVector__SWIG_1(ViewVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return maudeJNI.ViewVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    maudeJNI.ViewVector_clear(swigCPtr, this);
  }

  public ViewVector(int count, View value) {
    this(maudeJNI.new_ViewVector__SWIG_2(count, View.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return maudeJNI.ViewVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    maudeJNI.ViewVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return maudeJNI.ViewVector_doSize(swigCPtr, this);
  }

  private void doAdd(View x) {
    maudeJNI.ViewVector_doAdd__SWIG_0(swigCPtr, this, View.getCPtr(x), x);
  }

  private void doAdd(int index, View x) {
    maudeJNI.ViewVector_doAdd__SWIG_1(swigCPtr, this, index, View.getCPtr(x), x);
  }

  private View doRemove(int index) {
    long cPtr = maudeJNI.ViewVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new View(cPtr, false);
  }

  private View doGet(int index) {
    long cPtr = maudeJNI.ViewVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new View(cPtr, false);
  }

  private View doSet(int index, View val) {
    long cPtr = maudeJNI.ViewVector_doSet(swigCPtr, this, index, View.getCPtr(val), val);
    return (cPtr == 0) ? null : new View(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    maudeJNI.ViewVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
